### ISSUE TITLE
Display registers

### ISSUE THREAD

**Issue by Trass3r** [microsoft/MIEngine#1029]
As described in https://github.com/microsoft/MIEngine/issues/816#issuecomment-496785677.

**Comment by Trass3r** [comment]
@andrewcrawley It sort of works but the grouping is weird, most registers are in "others" and only r8 through r15 is in "CPU":
![grafik](https://user-images.githubusercontent.com/404623/90564558-d9e8fd80-e1a5-11ea-9c69-f50a1e096c49.png)

**Comment by andrewcrawley** [comment]
Probably you need to update the register name mapping code here: https://github.com/microsoft/MIEngine/blob/master/src/MIDebugEngine/Engine.Impl/EngineUtils.cs#L116

It doesn't look like we have one for x64 - looks like it's defaulting to the ARM map.

**Comment by Trass3r** [comment]
Indeed thx: b9e6b1225f6c4
Setting those variables doesn't really work though.
