### ISSUE TITLE
Natvis support for VSCode

### ISSUE THREAD

**Issue by graghavan007** [microsoft/MIEngine#1094]
Is MIEngine support for VSCode identical to MIEngine support for Visual Studio ?
Maybe my terminology is wrong. Are all Natvis schema objects supported by Visual Studio, also supported by VSCode ?
thanks
gopal

**Comment by WardenGnaw** [comment]
The VS Code MIEngine and Visual Studio MIEngine are the same and use the same [natvis reader](https://github.com/microsoft/MIEngine/blob/main/src/MIDebugEngine/Natvis.Impl/Natvis.cs). 

The Visual Studio MIEngine scenarios are Linux C++ Projects, Open Folder Debugging with launch.vs.json using cppdbg, or SSH Attach. 

For VS Code, this is where the launch.json has `type: cppdbg`. 

If you are talking about the Windows C++ Debugging scenario, it uses a different natvis reader. 

See https://code.visualstudio.com/docs/cpp/natvis

**Comment by graghavan007** [comment]
I wrote the following code :
class MyClass {    
public:             
    int myNum = 11; 
    std::string myString="hello"; 
};
Instantiated the class as: MyClass c = MyClass();
Here is my Natvis file:
	<Type Name="MyClass">
		<DisplayString>"Hello</DisplayString>
		<Expand>
			<CustomListItems>
				<Variable Name="ind" InitialValue="-1" />
				<Size>10</Size>
				<Loop>
						<Break Condition="ind == 5" />
						<Exec>ind += 1</Exec>
						<Item>ind,na</Item>
				</Loop>
			</CustomListItems>
		</Expand>
	</Type>

When I run this on Visual Studio/Windows I get:
![image](https://user-images.githubusercontent.com/4822725/104958611-2e76eb80-5985-11eb-8ee7-0d3d3c59fb48.png)
a list of items [0]-[5] with values of 0-5 as expected

When I run this on VSCode/Linux/gdb, I get *nothing*. Only the Raw View.
We are not using the debugger to get any values from the program, so I would have expected the same output in both cases ?
What is the difference ?
Thanks much
