### ISSUE TITLE
Different results on vscode and visual studio

### ISSUE THREAD

**Issue by graghavan007** [microsoft/MIEngine#1095]
I wrote the following code :
```
class MyClass {    
public:             
    int myNum = 11; 
    std::string myString="hello"; 
};
```
Instantiated the class as: MyClass c = MyClass();
Here is my Natvis file:
```
	<Type Name="MyClass">
		<DisplayString>"Hello</DisplayString>
		<Expand>
			<CustomListItems>
				<Variable Name="ind" InitialValue="-1" />
				<Size>10</Size>
				<Loop>
						<Break Condition="ind == 5" />
						<Exec>ind += 1</Exec>
						<Item>ind,na</Item>
				</Loop>
			</CustomListItems>
		</Expand>
	</Type>
```
When I run this on Visual Studio/Windows I get:
![image](https://user-images.githubusercontent.com/4822725/104958611-2e76eb80-5985-11eb-8ee7-0d3d3c59fb48.png)
a list of items [0]-[5] with values of 0-5 as expected

When I run this on VSCode/Linux/gdb, I get *nothing*. Only the Raw View.
We are not using the debugger to get any values from the program, so I would have expected the same output in both cases ?
What is the difference ?
Thanks much

_Originally posted by @graghavan007 in https://github.com/microsoft/MIEngine/issues/1094#issuecomment-762448128_

**Comment by WardenGnaw** [comment]
> When I run this on Visual Studio/Windows I get:

What kind of project do you have here?  The default Windows C++ project uses a different natvis reader than MIEngine.
I believe MIEngine does not support `Loop`.

To use MIEngine in Visual Studio, you will need to create a [project for WSL](https://devblogs.microsoft.com/cppblog/c-with-visual-studio-2019-and-windows-subsystem-for-linux-wsl/) or [use SSH for a Linux Project](https://docs.microsoft.com/en-us/cpp/linux/deploy-run-and-debug-your-linux-project?view=msvc-160).

**Comment by graghavan007** [comment]
Ok. I was confused because in item #1094, you had mentioned:
>> The VS Code MIEngine and Visual Studio MIEngine are the same and use the same natvis reader.
and i missed the subtlety that windows c+= uses a different natvis reader not MIEngine.
Thanks for clarifying

**Comment by WardenGnaw** [comment]
Ah sorry, I should have emphasized `Visual Studio MIEngine`. 

MIEngine is used for the "Linux" scenarios for Visual Studio. This includes using MinGW/Cygwin on Windows, but not projects built for VC++ that use vcxprojs.
