### ISSUE TITLE
add support for Wine

### ISSUE THREAD

**Issue by philipag** [microsoft/MIEngine#1105]
I am able to follow the wiki to connect a debug session from VS Windows to a WPF .Net 5.0 app running in a Ubuntu VM using Wine (WinHQ).  However, nothing other than attaching to the process works (e.g. breaking into the debugger causes an error). 

It would be GREAT if this were a tested and supported scenario. Wine is incredibly useful at making WPF apps run under Linux, and VS debugging not working seems to be the missing link at making this a truly easy way to port WPF apps to Linux.

**Comment by gregg-miskelly** [comment]
I am assuming you want to do managed debugging, correct? If so, this is probably not the right repo for this. I would probably suggest using "Help->Send Feedback->Suggest a feature..." from Visual Studio.

That said, you are using the version of .NET Compiled for Windows or for Linux? Or you using the vsdbg compiled for Windows or for Linux? It seems very unlilkely to me that this scenario would "just work", but the only way it would be to match the version of vsdbg to the version of the .NET Runtime.

**Comment by philipag** [comment]
Yes, managed debugging.

I just directly copied .net from my Windows PC to the Ubuntu VM.  vsdbg was created automatically in ~/.vs-debugger/vs2019 by VS when I used the Debug->Attach To Process menu and tried attaching with SSH.  This method worked even less than the method described in this wiki.  With the wiki method, when I stop debugging the Wine application is also terminated.  With the Debug->Attach To Process method even that does not happen.

This is a .Net 5.0 WPF app.

If this worked it would almost be a dream come true since I can run a rather complex app almost unmodified under Wine and the only missing link to enable streamlined development is a good managed debugger.

**Comment by gregg-miskelly** [comment]
**Disclaimer:** this is completely untested, and even if it works now, it may not work in the future. 

The only thing that has any chance at all of working would be to invoke the getvsdbg.sh script with '-r win7-x64' (so you get the Windows version of vsdbg) and manually set things up to launch the Windows vsdbg under wine. Using the Linux version of vsdbg with an app running on the Windows runtime will never work.

**Comment by philipag** [comment]
Yes, managed debugging.

I just directly copied .net from my Windows PC to the Ubuntu VM.  vsdbg was created automatically in ~/.vs-debugger/vs2019 by VS when I used the Debug->Attach To Process menu and tried attaching with SSH.  This method worked even less than the method described in this wiki.  With the wiki method, when I stop debugging the Wine application is also terminated.  With the Debug->Attach To Process method even that does not happen.

This is a .Net 5.0 WPF app.

If this worked it would almost be a dream come true since I can run a rather complex app almost unmodified under Wine and the only missing link to enable streamlined development is a good managed debugger.

**Comment by philipag** [comment]
Thanks for the suggestions @gregg-miskelly

I am happy to report that I can now attach to the WPF app running under Wine on Ubuntu.  Everything appears to work (breakpoints, debug output etc).  It's a bit slow but will make porting the app so much easier.

For anyone else who is interested here is what I did:

1. Follow the overall instructions at [https://github.com/microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio](url) to set things up (ssh etc).

2. Since Wine runs the WPF app, vsdbg also needs to run within Wine.  To get that I installed VS Code on Windows, installed the extension "C# for Visual Studio Code (powered by OmniSharp)", and copied "%USERPROFILE%\.vscode\extensions\ms-dotnettools.csharp-1.23.9\.debugger" to "~/vs-debugger"

3. Change launch.json like this so vsdbg runs under Wine as well:
`{
    "version": "0.2.0",
    "adapter": "C:\\...bin\\PLINK.EXE",
    "adapterArgs": "-i C:\\...\\ssh-ubuntu.ppk user@a.b.c.d -batch -T wine ~/.vs-debugger/vsdbg.exe",
    "configurations": [
        {
            "name": ".NET Core Ubuntu Wine Launch",
            "type": "coreclr",

            //"request": "launch",
            //"cwd": "/usr/bin/wine",
            //"program": "/home/user/debug/xyz.dll",

            "request": "attach",
            // replace with the process id you want to attach to. You can find this by running 'pidof' in the container
            // ex: `docker exec -it my_container_name pidof dotnet`
            // For Wine, use Wine TaskManager to get the PID of your WPF app (not the unix pid).
            "processId": 204
        }
    ]
}`

Note that "processId" must be obtained from the Wine task manager.  It is not the linux process.

**Comment by philipag** [comment]
Note that I copied .Net 5.0 from my windows machine directly to /home/username/.wine/drive_c/Program Files/dotnet in order to install this in my default wineprefix (Since my WPF app is a .Net 5 app).

**Comment by EliaTolin** [comment]
@philipag Is it possible to use VSStudio without VSCode?

@gregg-miskelly Is it possible to have a brief detailed official guide? It would be very useful, we are many Wine users. Thanks you.
