### ISSUE TITLE
a WindowsDebugLauncher implementation detail question

### ISSUE THREAD

**Issue by zt1106** [microsoft/MIEngine#1106]
In VSCode, the WindowsDebugLauncher.exe is used in the runInTerminal DAP protocol request to start the debugged program. But in WindowsDebugLauncher.exe's source code, I see It launches a gdb process, reads It's output and writes to server's named pipe, read server's input named pipe and writes to process's input. There is nothing about debugged process's io, but debugged process's io is shown in the terminal. How it's implemented? Where does the stdin/out/err come from?

**Comment by WardenGnaw** [comment]
WindowsDebugLaunch will spawn the executable and use WindowsDebugLauncher's stdin/stdout/stderr through redirection from the ProcessStartInfo.

https://github.com/microsoft/MIEngine/blob/74f810009496b87a0f6a7d592d691a303e099656/src/WindowsDebugLauncher/DebugLauncher.cs#L125-L127

**Comment by zt1106** [comment]
I'm not familiar with C#. But I don't see how WindowsDebugLaunch spawns the executable (debugged program) and get it's stdin/out/err. In code you posted, It launches a dbg (gdb.exe in Windows) process and redirects it's stdin/out/err to server through named pipe in the ReadWriteLoop, not to it's own stdin/out/err. So how debugged program's stdin/out/err is shown in the terminal? Am I wrong or It's not the code which launches the debugged program?

**Comment by zt1106** [comment]
the redirection arguments are added in LaunchOptions.cs. I finally found it.
