### ISSUE TITLE
gdb/debuginfod support for fetching source files

### ISSUE THREAD

**Issue by fche** [microsoft/MIEngine#1142]
Modern versions of GDB have learned to use the debuginfod protocol to fetch debuginfo and source files on the fly for programs / shared libraries it is debugging.  In the command line version of GDB, this works nicely e.g., in Fedora Rawhide.  When VSCODE drives gdb, part of this still works (the auto downloading of that content), but part doesn't (printing the source files).  This is probably because - by necessity - downloaded source files are located in a lookaside cache directory instead of the original DWARF-named directory/filename.  GDB knows the new name too, but something is getting lost on the way to VSCODE, because the latter tries to open only the original "/usr/src/debug/...." distro-build file names, not the $HOME/.cache/debuginfod_client/BUILDID/..... one with the downloaded content.  So users are greeted with a "Unable to open ...." popup error.

Please look into whether gdb/MI can pass VSCODE the proper downloaded source file name, and whether VSCODE can use that in addition.

https://sourceware.org/elfutils/Debuginfod.html

**Comment by fche** [comment]
It appears that a GDB bug is in your way:
https://sourceware.org/bugzilla/show_bug.cgi?id=27876

However, until that is fixed, VSCODE could perhaps fall back to the gdb `list` command (along with `set listsize`) to fetch gdb's view of the source file.  That part works okay for debuginfod-downloaded sources, as of gdb 10.
```
(gdb) set listsize 99999999999
(gdb) list 1
```

**Comment by Trass3r** [comment]
Fixed in gdb-12:
https://github.com/bminor/binutils-gdb/commit/9ac37a9ce607b790bea17c7782d73afecaaa916c

**Comment by gregg-miskelly** [comment]
Should this issue now be closed?

**Comment by fche** [comment]
Confirmed also that with git/master gdb (14.0.50.20230110-git), vscode's "step into" op on a basic hello-world printf() does download and render glibc sources!
