### ISSUE TITLE
[NuGet]: fail to build the MI solution of the box (using MSBuild)

### ISSUE THREAD

**Issue by ofirc** [Microsoft/MIEngine#121]
Problem
=======
When trying to build a fresh clone (checkout) of this repository, it will fail miserably
if you try it via CLI using MSBuild.

Details
=====
You have to open the solution with VS at least once in order to fetch ("nuget restore") the missing packages dependencies.

This is devastating for automated CI builds, as the NuGet packages are taken from .\packges
(this is dictated by the .csproj files), and thus need to be fetched and retrieved for every fresh clone.

I tried to Google it but couldn't find anything useful.

Does any one know how to solve/work-around that?

Is there some .csproj XML property that allows the missing NuGet packages to be retrieved
_prior_ to building?

Thanks,
Ofir

**Comment by chuckries** [comment]
The nuget restore is done by [BuildAndTest.proj](https://github.com/Microsoft/MIEngine/blob/master/BuildAndTest.proj) which is called by [build.cmd](https://github.com/Microsoft/MIEngine/blob/master/build.cmd). Are you experiencing an issue with this, or are you calling msbuild on the solution directly?

**Comment by ofirc** [comment]
Hi,
Thank you so much for your help, that was my problem :-).

I was calling msbuild on the solution directly, rather than using build.cmd.

Thanks,
Ofir
