### ISSUE TITLE
The result of GDB -exec evaluate request in all contexts is printed in debug console.

### ISSUE THREAD

**Issue by awulkiew** [microsoft/MIEngine#1236]
When `vscode.DebugSession.customRequest('evaluate', ...)` is called for expression starting with `-exec` the result is printed in debug console no matter what context was specified. It is not returned to the caller in `DebugProtocol.EvaluateResponse.result`. On the other hand if it doesn't start with `-exec` it is returned to the caller even if the context is `'repl'`.

**How to reproduce:**

In vscode extension, `registerDebugAdapterTrackerFactory`, define `onDidSendMessage` and catch `'stopped'` `'event'`. Then get `threadId` and execute `'stackTrace'` request to get `frameId`. Then call:
```
let exprArgs : DebugProtocol.EvaluateArguments = { expression: '-exec whatis name', frameId: frameId, context: 'watch' };
let test = await session.customRequest('evaluate', exprArgs);
```
with GDB and `name` being some identifier in C++ program.

**Comment by awulkiew** [comment]
FYI, I'm willing to work on a PR addressing this issue.

**Comment by tingleby** [comment]
We also have seen this behavior when working on an extension to enhance the debug session.

**Comment by WardenGnaw** [comment]
We will be shipping this in the next VS Code Release 1.12.1
