### ISSUE TITLE
Deleted MIEngine libraries

### ISSUE THREAD

**Issue by sangwook96** [microsoft/MIEngine#1316]
Hi
I am a developer for Tizen App.
During working, we got one issue.
In Visual Studio 2022 Community Preview (17.3.0 Preview 1.1), we tried to install https://marketplace.visualstudio.com/items?itemName=tizen.VSToolsTizen2022 (3.6.0.0)
After completing to installation, I find out the one issue.
“Visual Studio Tools for Tizen” has Tizen MIEngine internally
When a user installs “Visual Studio Tools for Tizen” vsix, “Visual Studio Tools for Tizen” tries to install embed MIEngine together.
Normally, After completion of the installation, we can see both “Visual Studio Tools for Tizen” and “Tizen MIEngine” libraries.
There is no issue till Visual Studio 17.2.3
But On the 17.3.X preview version, After installation the vsix, we can see both “Visual Studio Tools for Tizen” extension libraries but we can not see Tizen_MIEngine libraries.

As we analyzed, we find out the below steps.

Install “Visual Studio Tools for Tizen” extension libraries
Install Tizen_MIEngine libraries.
Execute vsfinalizer.exe
After that, Tizen_MIEngine libraries were deleted => It’s the issue which we ask you.
I also update in detail vsfinalizer.exe’s command lines.
Executing: “C:\Program Files\Microsoft Visual Studio\2022\Preview\common7\ide\vsfinalizer.exe” -Operation Modify -SKU Community -InstallationID 975af454 -InstallationName VisualStudioPreview/17.3.0-pre.1.1+32519.111 -InstallationVersion 17.3.32519.111 -InstallationWorkloads Microsoft.VisualStudio.Workload.CoreEditor,Microsoft.VisualStudio.Workload.NetCrossPlat,Microsoft.VisualStudio.Workload.ManagedDesktop,Microsoft.VisualStudio.Workload.NativeDesktop,Microsoft.VisualStudio.Workload.VisualStudioExtension -InstallationPackages

We make a workaround to debug it on the preview version(17.3.x), too
***Workaround***
src/MIDebugPackage/source.extension.vsixmanifest // Tizen MIEngine project
We changed from <Installation InstalledByMsi=“false” AllUsers=“true”> to <Installation InstalledByMsi=“false”>

src/Tizen.VisualStudio.VsixSetup/source.extension.vsixmanifest // Visual Studio Tools for Tizen
We changed from <Installation AllUsers=“true”> to <Installation>

src/Tizen.VisualStudio.VsixSetup/Tizen.VisualStudio.VsixSetup.csproj // Visual Studio Tools for Tizen
Removed the lines
<PropertyGroup>
<GetVsixSourceItemsDependsOn>$(GetVsixSourceItemsDependsOn);AddToVsixSources</GetVsixSourceItemsDependsOn>
</PropertyGroup>
<Target Name=“AddToVsixSources”>
<ItemGroup>
<_Contents Include=“$(OutputPath)\DeployedContents**” />
<VSIXSourceItem Include=“@(_Contents)”>
<VSIXSubPath>Tizen\VisualStudio%(_Contents.RecursiveDir)</VSIXSubPath>
<InstallRoot>MSBuild</InstallRoot>
</VSIXSourceItem>
</ItemGroup>
</Target>

We can **reproduce** it in the sample projects also using the following steps,

1. Create a sample dependent C# vsix project from the project wizard, change the option in source.extension.manifest file to allusers=true (e.g - <Installation AllUsers=“true”>)and generate vsix.
2. Create a sample main C# vsix project, change the option to allusers=true in source.extension.manifest file(e.g - <Installation AllUsers=“true”>), copy the dependent vsix generated above, add dependency as embedded VSIX, and create main VSIX.
example code,
`<Dependencies>`
`<Dependency Id=“Microsoft.Framework.NDP” DisplayName=“Microsoft .NET Framework” d:Source=“Manual” Version=“[4.5,)” />`
`<Dependency d:Source=“File” DisplayName=“VSIXProject1” Id=“VSIXProject1.61d8d5f9-ff1b-483f-8e85-71594cb37f6b”` `Version=“[1.0,2.0.0.0)” d:InstallSource=“Embed” Location=“VSIXProject1.vsix” />`
`</Dependencies>`

Installation in Visual studio 2022 17.2.3 version
-> Both the main and dependent VSIX is installed.

Installation in Visual Studio 2022 Preview 17.3.1 version
-> Only the main VSIX is installed, the dependent VSIX is not installed.

For the Official version like community or professional,
we need to have `AllUsers=“true”`
If  there is no `AllUsers=“true”` on the vsix, we can not install the vsix.

But for preview version like community preview (17.3.x)
we should not have `AllUsers=“true”`
If there have `AllUsers=“true”` on the vsix, we can not debug tizen.net app 

Could we use  `AllUsers=“true”` on the preview version, too?

Thanks

**Comment by sangwook96** [comment]
We are waiting for your help.

**Comment by WardenGnaw** [comment]
Moving to https://github.com/microsoft/VSExtensibility/issues/95
