### ISSUE TITLE
[gdb] -exec is broken in 1.12.4/1.12.3

### ISSUE THREAD

**Issue by sbobko** [microsoft/MIEngine#1347]
### Environment

- OS and version: Ubuntu 20.04.4 LTS
- VS Code: 1.70.2
- C/C++ extension: 1.12.4 / 1.12.3

### Bug Summary and Steps to Reproduce

Bug Summary:
Trying to use -exec results in nothing and crashes.

v1.12.4
![image](https://user-images.githubusercontent.com/46919374/187901915-4860cca3-bac3-4052-b3b9-fffc6edd0ee1.png)
v1.12.3
![image](https://user-images.githubusercontent.com/46919374/187902164-4795151b-1e9d-4b97-96d8-90fa9f45d99a.png)

When rolling back two versions, the problem disappears:
v1.11.5
![image](https://user-images.githubusercontent.com/46919374/187901653-0b490cde-2a64-4698-bdbd-7cd2c7f15164.png)

Steps to reproduce:
1. Start debugging using gdb
2. run -exec any_command in debug consol
expected: ![image](https://user-images.githubusercontent.com/46919374/187901653-0b490cde-2a64-4698-bdbd-7cd2c7f15164.png)
Actual:
![image](https://user-images.githubusercontent.com/46919374/187902164-4795151b-1e9d-4b97-96d8-90fa9f45d99a.png)

### Debugger Configurations

```shell
"description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
```

### Debugger Logs

```shell
Nothing
```

**Comment by sbobko** [comment]
upd:
Commands that start with - work, the example in the screenshot. Perhaps this will tell you more than it tells me.
![image](https://user-images.githubusercontent.com/46919374/187913911-f8e44020-0dca-486b-9447-8bfc80dcff92.png)

**Comment by WardenGnaw** [comment]
We will use the one in cpptools to track this issue. https://github.com/microsoft/vscode-cpptools/issues/9827
