### ISSUE TITLE
vscode debugger pauses on SIGINT after adding breakpoint (remote gdb)

### ISSUE THREAD

**Issue by FabioGNR** [microsoft/MIEngine#1382]
When you add a breakpoint in vscode using ms-vscode.cpptools v1.13.9 the debugger pauses on SIGINT "Interrupted".
I believe this was introduced with #1366.
src/MICore/Debugger.cs contains `var res = CmdAsync("-exec-interrupt", ResultClass.done);` which to me would appear to always generate SIGINT, but I could be wrong here.

GDB version 10.2, target is ARM.
Doing remote debugging on target from a Ubuntu 22 system.

I will try a smaller repro scenario which I can share.

**Comment by FabioGNR** [comment]
Small gist to repro: https://gist.github.com/FabioGNR/42a2f1c18e4c5820022f5f7242e978d7
It only happens with remote debug (i.e. gdbserver)

**Comment by aallrd** [comment]
Reproduce the issue with GDB 13.1 on RHEL 8.
