### ISSUE TITLE
Is MIEngine used in linux vscode?

### ISSUE THREAD

**Issue by navinp0304** [microsoft/MIEngine#1483]
Hi,
        I found build instructions for MIEngine on windows using visual studio and it builds few dlls.
        How does vscode on linux use ( c++ microsoft extension ) code from MIEngine like Natvis.cs ?

Regards,
Navin

**Comment by gregg-miskelly** [comment]
Yes, MIEngine is the debugger used with the C++ extension. I am not totally sure I understand your question, but the way debugging works in VS Code is that various "debug adapters" are registered with VS Code. A Debug Adapter is usually an executable that speaks the [Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) between itself and a client (where the client is VS Code in this case) and then it somehow communicates to the target process. In the case of MIEngine, this is accomplished by talking to GDB/LLDB-mi over GDP's "machine interface" protocol. More information on how this works is in the wiki. [Here](https://github.com/microsoft/MIEngine/wiki/Architecture-of-the-MIEngine) is a good place to start.

**Comment by navinp0304** [comment]
How does MIEngine work on linux ? I can see that it only builds .dll not .so.

**Comment by gregg-miskelly** [comment]
.NET libraries normally compile to '.dll' on all platforms. Only the runtime itself (ex: libcoreclr.so) are a .so.

**Comment by navinp0304** [comment]
> .NET libraries normally compile to '.dll' on all platforms. Normally, only the .NET Runtime itself (ex: libcoreclr.so, etc) is a .so.
@gregg-miskelly 

Now in that case why do we have 2 sln in miengine. Which one to use for linux ?

**Comment by gregg-miskelly** [comment]
MIDebugEngine.sln contains the full set of projects in this repo, this includes several projects that are only used on Windows + full Visual Studio. This solution is only buildable on Windows.

MIDebugEngine-Unix.sln contains the subset of projects that are used in the VS Code scenario. This solution is buildable on any platform.
