### ISSUE TITLE
Function breakpoints don't work

### ISSUE THREAD

**Issue by olizit** [Microsoft/MIEngine#165]
I try to add a function breakpoint before starting target. At debugger startup, function breakpoint failed. 
Can I used function breakpoint ? Is it implemented in MIEngine ?

**Comment by gregg-miskelly** [comment]
No, the MIEngine doesn't currently support them. It doesn't look like we have an issue tracking this. So we can use this one.

**Comment by olizit** [comment]
I'm working on a PR

**Comment by wiktork** [comment]
Completed with #179
