### ISSUE TITLE
MI Engine should address breakpoints

### ISSUE THREAD

**Issue by Pallak491** [Microsoft/MIEngine#182]
Address breakpoints are currently not supported ('Unsupported Breakpoint Type").
Are there any plans to add this in the future?
It would sometimes be helpful to be able to set breakpoints in the disassembly window. The restriction to source lines prevents inspection of code that covers a single source line, but consists of multiple instructions. Would also help to get around in code that has no debug info. (libraries)

**Comment by gregg-miskelly** [comment]
We don't have immediate plans to support these, though certainly doing so makes sense. You should be able to hack around it for now by opening the VS command window and executing `Debug.MIDebugExec break *address`.

**Comment by paulmaybee** [comment]
Fixed #302
