### ISSUE TITLE
How to work with DebugServer and DebugServerArgs

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/MIEngine#191]
Hi,

My first post here: let me congratulate you on this truly awesome tool!
I work on embedded systems and being able to debug from Visual Studio is a dream come true. :smile: 

Now my issue.
I want to be able to debug an ELF using gbd and OpenOCD.
Right now I can start the debug session but I need to launch OpenOCD first from a command prompt.
Tried using DebugServer and DebugServerArgs to start it but it's not working. 
1) I'm understanding the correct purpose for these two settings?
2) Follows my LocalLaunchOptions for you to review

<LocalLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
    MIDebuggerPath="arm-none-eabi-gdb.exe"
    MIDebuggerServerAddress="localhost:3333"
    ExePath="blink.elf"
    TargetArchitecture="arm"
    MIMode="gdb"
    DebugServer="C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-201601101000-dev\bin\openocd.exe"
    DebugServerArgs="stlink-v2-1.cfg -f board\stm32f4discovery.cfg"
/>

Thanks!

**Comment by paulmaybee** [comment]
You will need a few more parameters to set up the server


1.       The ServerStarted parameter tells the debugger what to look for in the server output stream to signify that the server is listening on its port. For OpenOCD we usually use:

ServerStarted= "Info\\ :\\ [\\w\\d\\.]*:\\<file://w/d/.%5d*:/> hardware"


2.       OpenOCD also writes its status messages to stderr, not stdout, so you need to tell the debugger to look there:

FilterStderr=true

If there are any custom commands that you need to issue to your board (through OpenOCD) in order to initialize debugging then you may need other parameters too. For example on an Arduino Zero I use these:

<SetupCommands>
<Command>target remote localhost:3333</Command>
<Command>file blink.elf </Command>
<Command>monitor reset halt</Command>
</SetupCommands>
<CustomLaunchSetupCommands>
<Command>monitor reset init</Command>
</CustomLaunchSetupCommands>
<LaunchCompleteCommand> exec-continue</LaunchCompleteCommand>

**Comment by josesimoes** [comment]
@paulmaybee thank you for your explanations. I did manage to get further, but openOCD still fails to load properly....

Here is my current LocalLaunchOptions file:

<LocalLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
    MIDebuggerPath="E:\GNU_Tools_ARM_Embedded\5_2_2015q4\bin\arm-none-eabi-gdb.exe"
    MIDebuggerServerAddress="localhost:3333"
    TargetArchitecture="arm"
    MIMode="gdb"
    ExePath="E:\GitHub\netmf-interpreter\BuildOutput\THUMB2FP\GCC5.2\le\FLASH\debug\STM32F4DISCOVERY\bin\tinyclr_net.axf"
    DebugServer="C:\Program Files\GNU ARM Eclipse\OpenOCD\0.10.0-201601101000-dev\bin\openocd.exe"
    DebugServerArgs=" -f board\stm32f4discovery.cfg"
    ServerStarted= "Info\\ :\\ [\\w\\d\\.]*:\\&lt;file://w/d/.%5d*:/&gt; hardware"
    ServerStartedTimeout="20000"
    FilterStderr="true">
<SetupCommands> 
    <Command>target remote localhost:3333</Command> 
    <Command>monitor reset halt</Command> 
</SetupCommands> 
<CustomLaunchSetupCommands> 
    <Command>monitor reset init</Command> 
    <Command>break main</Command>
</CustomLaunchSetupCommands> 
<LaunchCompleteCommand>exec-continue</LaunchCompleteCommand> 
    
</LocalLaunchOptions>

Follows the output of OpenOCD when started from a cmd prompt

GNU ARM Eclipse 64-bits Open On-Chip Debugger 0.10.0-dev-00287-g85cec24-dirty (2016-01-10-10:13)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
adapter speed: 2000 kHz
adapter_nsrst_delay: 100
none separate
srst_only separate srst_nogate srst_open_drain connect_deassert_srst
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : Unable to match requested speed 2000 kHz, using 1800 kHz
Info : clock speed 1800 kHz
Info : STLINK v2 JTAG v23 API v2 SWIM v0 VID 0x0483 PID 0x3748
Info : using stlink api v2
Info : Target voltage: 2.897285
Info : stm32f4x.cpu: hardware has 6 breakpoints, 4 watchpoints


I've set a breakpoint in line 48 @ ServerTransport and I get up to the line:
Info : Unable to match requested speed 2000 kHz, using 1800 kHz

After that a exception throws and the message saying unable to start debug. no process associated with this object.
Any ideas?

**Comment by paulmaybee** [comment]
Looks like there was a cut-paste error above in my original message, ServerStarted line should read:

ServerStarted= "Info\\ :\\ [\\w\\d\\.]*:\\ hardware"

**Comment by paulmaybee** [comment]
Yikes. And trying again ...

ServerStarted= "Info\\\\ :\\\\ [\\\\w\\\\d\\\\.]*:\\\\ hardware"

**Comment by josesimoes** [comment]
Got it working!
I add to remove the double \\ as these don't seem to be needed in the XML file.
I also had to add a line to load the elf file "manually" otherwise the symbols and code weren't loaded.
Still getting some exceptions with the breakpoint set and on pausing but I'll get to that latter.

Thanks so much for your help! :smile:
