### ISSUE TITLE
natvis diagnostics

### ISSUE THREAD

**Issue by Trass3r** [microsoft/MIEngine#192]
Diagnostics are crucial to figure out why visualizations aren't working.
But with remote debugging they aren't printed to the Debug Output pane.

**Comment by todi1856** [comment]
Not sure, if this is related, but it seems MiEngine doesn't respect Visual Studio option "Natvis diagnostic messages" in Options->Debugging->Output Window

**Comment by Trass3r** [comment]
For the record in VSCode the only way to get some diagnostics at all is add this to launch.json:

```json
"logging": {
	"engineLogging": true
}
```

But the natvis lines are drowning in all the other logs.
And they are not very helpful either:
```
(24601) <-1207-var-create - * "this"
(24601) ->1207^done,name="var17",numchild="1",value="0x5555557d3aa0",type="const class {...} *"
(24602) ->1208^done,name="var18",numchild="2",value="{...}",type="const (anonymous namespace)::...."
(24746) Natvis failed to parse typename: const class {...} *
```

You don't get anything about why a visualizer has been applied or why not like in VS.
