### ISSUE TITLE
setting breakpoint when loading compiled image

### ISSUE THREAD

**Issue by josesimoes** [Microsoft/MIEngine#194]
I'm using the MIEngine to load a ELF file and debug with GDB.
I've reached the point of having the image loaded on the flash.
Now I'm trying to set a break point at a function where the debugger should stop. Tried with SetupCommands and CustomSetupCommands without success.
How can I do this?

Thanks,

**Comment by paulmaybee** [comment]
Have you tried opening the source file in VS and placing the breakpoint on the line before you start debugging?

**Comment by josesimoes** [comment]
The ELF file is a result of linking several obj. Those obj include the debug information. I'm not able to open the ELF file in VS...

If I use:

<CustomLaunchSetupCommands> 
    <Command>monitor reset init</Command> 
    <Command>break main</Command>
</CustomLaunchSetupCommands> 

As you suggested in the other issue I've opened, the breakpoint is set at "main" and if I pause in VS I can see the source code.

**Comment by paulmaybee** [comment]
The ELF file should contain all the symbols and get opened by gdb when you start debugging. If you place a breakpoint by line (that is, open the source file and click on the source line) before you start it should bind as soon as gdb reads the symbols from the ELF file. If you are not getting symbols read correctly then you also would not be seeing source, step lines, or seeing the local variables.

**Comment by josesimoes** [comment]
I can see the break point using gdb  break command.
I failed to explain that I can't set the break point in the source file because the ELF file is complied and linked outside of VS.
Anyway it's working as expected. Thanks! :+1:
