### ISSUE TITLE
csharp debugger based on MIEngine 

### ISSUE THREAD

**Issue by chunseoklee** [Microsoft/MIEngine#245]
I have a question about extensibility of MIEngine.
I have seen the csharp debugging demo(VS Code on Mac) shown in connect 2015.
Is the demo based on MIEngine ? 
How can gdb/mi protocol control csharp managed code debugging information ?
Thank you.

**Comment by caslan** [comment]
This should help clarify: https://github.com/Microsoft/MIEngine/wiki/What-is-CLRDBG

**Comment by manu-silicon** [comment]
Is clrdbg already available?

**Comment by gregg-miskelly** [comment]
There was a preview version that shipped for use in the C# VS Code extension that works with [CLI build 1598](http://dotnet.github.io/getting-started/), and we are working on scripts and documentation that I hope to release in the next couple of days that work with the latest versions of .NET CLI. It will release more officially with the rest of .NET Core RC2.

**Comment by manu-silicon** [comment]
@gregg-miskelly Looking forward to this!

**Comment by chunseoklee** [comment]
@gregg-miskelly @chuckries 
Is there any plan or ETA for open source release of clrdbg ? 
I would try to port clrdbg to Linux on ARM.

**Comment by gregg-miskelly** [comment]
@chunseoklee lets follow up over email as your team has unique needs.
