### ISSUE TITLE
can you support old VS version?

### ISSUE THREAD

**Issue by kigkrazy** [Microsoft/MIEngine#291]
my code is in the old VS.So I can't use this tool!

**Comment by chuckries** [comment]
What version of Visual Studio are you using? And what scenario do you want to use MIEngine for?

**Comment by kigkrazy** [comment]
VS2012 !!! My project is built by VS2012~ there are many procject in my company!

**Comment by gregg-miskelly** [comment]
Visual Studio installs side-by-side (meaning you can have multiple version of Visual Studio installed at the same time) so if your company qualifies, you can install [VS 2015 Community Edition](https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx) for free.

If your company is too large to qualify, you could probably build your own version of this package and install the .vsix into VS2012 with little effort.
