### ISSUE TITLE
VSD3DDebug interface and GPU debugging perf on VS

### ISSUE THREAD

**Issue by ofirc** [Microsoft/MIEngine#355]
Hi,
I believe this is the best forum for these kinds of questions.

The project I'm working on uses an MIEngine fork that supports debugging
of GPGPU kernels on the GPU via Visual Studio.

We are really pleased with the infrastructure provided by MSFT and it 
achieves most of the goals, but we still have room for improvements.

**1) Are there some customizations for a GPU-targeted MIEngine?**
    The MSDN page [1] suggests the following:
   "Independent hardware vendors who want to support GPU debugging in Visual Studio must create a 
    DLL that implements the VSD3DDebug interface and targets their own drivers."

    But unfortunately this interface is no where to be found.

**2) Performance and scalability**
    The GPU we are targeting contains a lot of *cores*,
    each core is capable of running multiple threads.
    When the threads window in VS is opened and a breakpoint is hit, we've noticed a severe
    perf degradation, because it seems like this window is not *lazily* evaluated
    (i.e. only for the threads that fit in within the window size, but for the entire active threads).

    Is there a way to re-use the GFX debugging VS tool windows,
    or improve somehow the performance?

    It kind of connects to the first question.

Thanks,
Ofir

[1] https://msdn.microsoft.com/en-us/library/hh873126.aspx

**Comment by gregg-miskelly** [comment]
For 1: VSD3DDebug uses a totally different technique for plugging in a GPU debugger into VS. You wouldn't use the MIEngine at all if you went that way. @paulmaybee was involved in that project and so may be able to help you there.

For 2: I am not sure how much success you are going to have making the threads Window work well for GPU scenarios with oodles of threads. Paul may also be able to comment more on this one.

**Comment by ofirc** [comment]
Thanks for the help Greg!
