### ISSUE TITLE
Format specifiers don't work with natvis

### ISSUE THREAD

**Issue by AndrewBrianHall** [microsoft/MIEngine#4]
Does not support the format specifiers yet like ,su for unicode strings.  See https://msdn.microsoft.com/en-us/library/75w45ekt%28v=vs.140%29.aspx

**Comment by Trass3r** [comment]
This is really bad, especially since it renders existing natvis files that work fine on Windows useless.
It even prints ,s8 as a double.
![image](https://cloud.githubusercontent.com/assets/404623/13202457/36c21126-d89c-11e5-880f-be35dd8f2221.png)

**Comment by paulmaybee** [comment]
The MIEngine relies on gdb (or lldb) to do its expression evaluation and data formatting so as a result the natvis capabilities are somewhat contrained. There are many Windows natvis features that are not supported in the MIEngine natvis. That said, the engine could do a better job of "ignoring" format specifiers it is not able to handle so that it would be easier to copy/paste from windows natvis files.

**Comment by Trass3r** [comment]
So post-processing isn't possible I guess.
But yeah it should at least ignore the unsupported modifiers.

**Comment by zhihaoy** [comment]
Is that possible to reformat the result obtained from MI?  I think this feature is quite important, we really need flags for floating point numbers for numeric software.
Also, I would like to know whether `na` and `sb` are feasible to support.

**Comment by gregg-miskelly** [comment]
It depends on the format specifier. `na` and `sb` are probably both implementable. If you are interested in trying to implement this I can try and dig up the code to where we support `,x` as an example.

**Comment by EricHripko** [comment]
Hi @gregg-miskelly! I am interested in contributing `na` and (especially) `s` support in Natvis. [Variables.cs](https://github.com/microsoft/MIEngine/blob/2a2d61940a4307f8c4bcdde33058512436641816/src/MIDebugEngine/Engine.Impl/Variables.cs) seems like the starting point for this - do you have any other tips for trying to implement this? Thanks 🙂

**Comment by Trass3r** [comment]
The starting point is https://github.com/microsoft/MIEngine/blob/62b1e7055ae0f84dd7332eb0699e352aa42d8d69/src/MIDebugEngine/Engine.Impl/Variables.cs#L344
