### ISSUE TITLE
clrdbg?

### ISSUE THREAD

**Issue by waywardmonkeys** [Microsoft/MIEngine#40]
Is there any information about what clrdbg is, where it is available from, etc? The README doesn't link to anything for it, so it isn't clear (to me at least).

**Comment by paulmaybee** [comment]
clrdbg still has a lot of work to be done before it is a usable debugger, but this is how we expect cross-platform CoreCLR debugging to work. If you are interested, you can watch a demo of clrdbg on Linux in action as part of the //Build/ conference day one keynote. The clrdbg part is at the 26:00 mark. Link: http://channel9.msdn.com/Events/Build/2015/KEY01

**Comment by gregg-miskelly** [comment]
BTW: We now have a wiki article for it: [link](https://github.com/Microsoft/MIEngine/wiki/What-is-CLRDBG)
