### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by borgdylan** [microsoft/MIEngine#406]
I ma trying to fix an issue with a custom language that might require building the MIEngine from source. Can this be built on Linux? The source code refers to old TFMs like dnxcore50.

**Comment by gregg-miskelly** [comment]
No, the MIEngine can currently only be built on Windows.

**Comment by WardenGnaw** [comment]
The MIEngine repo can now be built on linux via .NET 5 SDK when building the `MIDebugEngine-Unix.sln`. This solution contains the projects used on Unix platforms.
