### ISSUE TITLE
Cannot add private Nuget feed

### ISSUE THREAD

**Issue by McMlok** [Microsoft/MIEngine#408]
Hello,

I use Visual Studio Tools for Docker and they use your script GetClrDbg.sh. In this script is generated NuGet.Config but when I need to use my private Nuget feed I don't have chance to add it.

**Comment by chuckries** [comment]
@McMlok What are you trying to get from your private NuGet feed? The NuGet.config file generated by GetClrDbg.sh script is used by our own dotnet restore command to obtain the debugger binaries and should not be used for other nuget scenarios.

**Comment by McMlok** [comment]
It's because I have problem with corporate proxy and we use our Nexus server as Nuget server for our private nugets and as proxy for nugets from nuget.org.

**Comment by chuckries** [comment]
I will look into fixing this properly, but here is a quick workaround:
1. In your `Dockerfile.debug` there should be a reference to [https://raw.githubusercontent.com/Microsoft/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh](https://raw.githubusercontent.com/Microsoft/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh). This is hosted from the getclrdbg-release branch of the MIEngine repository.
2. Fork MIEngine to your own repo, and update `GetClrdDbg.sh` to generate the `NuGet.config` that you need. Make sure you do the work in the getclrdbg-release branch, as this has the most up to date version of the script.
3. Change your `Dockerfile.debug` to point to the raw view of your new 1GetClrDbg.sh` script in your MIEngine repo.
4. Clean your solution and rebuild/redeploy.

**Comment by McMlok** [comment]
Thanks, workaround works. But now VisualStudion cannot attach debugger. With message "Error calling docker-machine ip for docker machine default. Check to see if it is running and accepting connections.Security error." But this is another story.

**Comment by chuckries** [comment]
@NCarlsonMsft or @dbreshears may be able to help you with your docker issue. I am going to mark this issue closed since docker is outside the scope of MIEngine.

**Comment by dbreshears** [comment]
@McMlok.    Are you using  Docker Toolbox or Docker For Windows?   If you replace "default" with empty string from Docker.props file in VS, does the issue go away?

**Comment by McMlok** [comment]
I'm using Win7, VS2015 Update3, Docket toolbox  1.12. If I have empty string in props I can not build image. If I run project in release mode it is same but when I open browser manualy and navigate to docker host IP application runs. I think its some security settings on my corp PC, proxy, firewall, anti virus, global politics. But I cant find any clues where to search.
