### ISSUE TITLE
Vs to VS build error

### ISSUE THREAD

**Issue by chunseoklee** [microsoft/MIEngine#419]
When I tried to build the latest master, I got a build error which ask for me to modify Vs to VS in teo function names(I dont remember since I am out of office) If I follow the suggestion, build error is gone. However, the strange thing is that it does not happen on my colleage's setting. 
I am building with VS 2015 professional with extensibility update 3.

**Comment by chunseoklee** [comment]
The build error as follows: (sorry for korean log)
```
>E:\dev\MIEngine\src\DebugEngineHost.Stub\DebugEngineHost.ref.cs(233): error CA1709: Microsoft.Naming : 멤버 이름 'HostLoader.VsCoCreateManagedObject(HostConfigurationStore, Guid)'에서 'Vs'의 대/소문자를 'VS'(으)로 수정하십시오.
>  코드 분석 완료 -- 오류: 1개, 경고: 0개
```
Corresponding Source code : 
```
[System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Co")]
        public static object VsCoCreateManagedObject(HostConfigurationStore configStore, Guid clsid)
        {
            throw new NotImplementedException();
        }
```

**Comment by sonyps5201314** [comment]
below is bugfix:
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Vs")]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709:IdentifiersShouldBeCasedCorrectly", MessageId = "Co")]
        public static object VsCoCreateManagedObject(HostConfigurationStore configStore, Guid clsid)
        {
            throw new NotImplementedException();
        }

**Comment by gregg-miskelly** [comment]
@sonyps5201314 your fix looks good to me. Would you wind sending in a PR?

**Comment by WardenGnaw** [comment]
Not seeing this issue on the main branch for VS 2019 or VS 2022 Preview. 

Closing as resolved.
