### ISSUE TITLE
MIEngine distribution

### ISSUE THREAD

**Issue by manu-silicon** [Microsoft/MIEngine#421]
I've been able to make MIEngine work with clrdbg which is great. Now the next step is to install MIEngine in Visual Studio for our users. How are we supposed to proceed since there is no MIEngine extensions available for VisualStudio?

Thanks for the clarification

**Comment by seanshpark** [comment]
@manu-silicon , btw, how did you get the `clrdbg` ?

**Comment by seanshpark** [comment]
@manu-silicon , can https://github.com/Microsoft/MIEngine/wiki/Redistribution page be a help?

**Comment by manu-silicon** [comment]
@seanshpark Indeed that's what I was looking for. I found the clrdbg for Linux by following the instructions at https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio

**Comment by gregg-miskelly** [comment]
Sorry for not responding earlier, but I think you two solved each others problems so I am going to close this for now.
