### ISSUE TITLE
Question, plan to support .NETCore on Linux machines

### ISSUE THREAD

**Issue by seanshpark** [Microsoft/MIEngine#454]
Hi, is there any plan to add something like `LinuxDebugLauncher` so that we can debug code running in  remote Linux machine running .NET Core binaries? connected through SSH/plink or something.

**Comment by DarioGi** [comment]
The only way I was able to get it to work is by using Xamarin Studio and SSHDebugger extension, and mono. You would be able to run any .NET library/executable using mono. This will allow you to debug such binaries on Linux from a remote machine.

**Comment by gregg-miskelly** [comment]
You can connect to a Linux machine using any of the launch options that we have. 

If you are using Visual Studio, we will soon be releasing built-in support for SSH using [SSHLaunchOptions](https://github.com/Microsoft/MIEngine/blob/ed0323fe0e0fc54d27fc2c50c8ea3b22c8823629/src/MICore/LaunchOptions.xsd#L340).

If you are using either VS 2015 Update 3, or VS Code, you can use [PipeLaunchOptions](https://github.com/Microsoft/MIEngine/blob/ed0323fe0e0fc54d27fc2c50c8ea3b22c8823629/src/MICore/LaunchOptions.xsd#L276) using plink or ssh as the underlying pipe executable. Instructions are on https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio.

One note if you are adding some sort of Visual Studio extension which will launch the MIEngine for .NET Core debugging -- eventually we be making some changes to how this works that will require some tweaks to this code. Should be easy to make, but this is just a heads up that someday it will happen.

**Comment by seanshpark** [comment]
@gregg-miskelly , thanks !
