### ISSUE TITLE
NullReferenceException on _configStore access 

### ISSUE THREAD

**Issue by chunseoklee** [Microsoft/MIEngine#459]
commit: 6e57df47
When debugging on experimental instance, MIEngine throws nullreference exception at the _configStore accesss as the following code( ad7engine.cs : 711 )
```
public int SetEngineGuid(ref Guid guidEngine)
{
            _engineGuid = guidEngine;
            _configStore.SetEngineGuid(_engineGuid);
            return Constants.S_OK;
}
```
Should I add into VS2015 something ?

**Comment by gregg-miskelly** [comment]
That should be set at https://github.com/Microsoft/MIEngine/blob/master/src/MIDebugEngine/AD7.Impl/AD7Engine.cs#L464 which should always be called before SetEngineGuid. Are you seeing any calls to `SetRegistryRoot`?

**Comment by chunseoklee** [comment]
@gregg-miskelly That function is not called before nullreferenceexception, which make me confused. I have reinstalled VS2015 and tried it, but failed with the same exception. ( I am using VS2015 professional update 3)

**Comment by gregg-miskelly** [comment]
hmm... I can't really think of a reason why that could happen. Can you save a full dump of devenv at the NullReferenceException. I will start an email conversation with you on how to send me the dump.

**Comment by chunseoklee** [comment]
This is casued by my internal problem on Windows runtime.
