### ISSUE TITLE
Replace .pkgdef with RegistrationAttribute

### ISSUE THREAD

**Issue by phofman** [Microsoft/MIEngine#46]
Having a [Microsoft.MIDebugEngine.pkgdef](../blob/master/src/MIDebugEngine/Microsoft.MIDebugEngine.pkgdef) with hardcoded features supported and GUIDs of the debug-engine could be improved and simplified. This file could be generated directly from source code to be always up-to-date by dedicated RegistrationAttribute. Especially, it will make the redistribution easier.

I already used the dedicated [DebugEngineRegistrationAttribute](/phofman/vs-plugin/blob/develop/src_vs2012/Package/Registration/DebugEngineRegistrationAttribute.cs) attribute [here](/phofman/vs-plugin/blob/develop/src_vs2012/Package/BlackBerryPackage.cs#L73) in my plugin.
I could port it here instantly. What properties should be exposed by this attribute to cover all features of MIEngine?

**Comment by phofman** [comment]
Forget to mention - this should also remove this ugly `Install.cmd` - or at least the need of any registry manipulations as the path to 'experimental' engine could be precalculated by the attribute too.

**Comment by chuckries** [comment]
Thanks for suggestion! This would certainly be doable, but we prefer a static pkgdef file. One reason for this is that we may add registry keys to the pkgdef in the future, and with an attribute this would require adding new C# code instead of simply authoring a line into the pkgdef file.
