### ISSUE TITLE
[Redistributable] Experimental instance of Visual Studio doesn't find custom debug engine

### ISSUE THREAD

**Issue by Dmitri-Botcharnikov** [Microsoft/MIEngine#460]
After changing GUIDs as stated in [Redistribution](https://github.com/Microsoft/MIEngine/wiki/Redistribution) the MIDebugLaunch command no longer finds custom debug engine, instead it loads installed version of the engine. Is there a way to start my version of engine with MIDebugLaunch command?

**Comment by gregg-miskelly** [comment]
@Dmitri-Botcharnikov if you change GUIDs you are creating a new side-by-side debug engine. So, if you still want command window integration, you would want to still include the MIDebugPackage, but you would need to rename the 'MIDebugLaunch' command to your own thing. I will add notes on this to the wiki page.

**Comment by Dmitri-Botcharnikov** [comment]
I've renamed launch command but now it seems like experimental instance of VS doesn't find my engine by GUID:
```
The debugger is not properly installed.  Cannot debug the requested type of code.  Run setup to install or repair the debugger.
```
This message is result of COM exception form call to `debugger.LaunchDebugTargets4`
Should I do something to register my debug engine?

**Comment by gregg-miskelly** [comment]
The debugger engine is registered through the .pkgdef file. Make sure you have the new GUID there. You can check what is in the registry by looking at HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0_Config[Exp][_number]. Where the '[Exp]' suffix is used if you are using the experimental instance of VS (this will be true if you are F5'ing the package project). The '[_number]' suffix can sometimes be there if there are multiple copies of the 'config cache'. If you can't figure out which one is being used you can delete them all, do a clean build of the project, and it should come back.

**Comment by Dmitri-Botcharnikov** [comment]
@gregg-miskelly: thanks a lot! I finally found cause of error: one need to change CodeBase parameter value in the .pkgdef file to reflect renaming of .dll file.
