### ISSUE TITLE
[Redistributable] Errors while building renamed assemblies

### ISSUE THREAD

**Issue by Dmitri-Botcharnikov** [Microsoft/MIEngine#461]
After renaming assemblies according to [Redistribution](https://github.com/Microsoft/MIEngine/wiki/Redistribution) the build fails with errors like the following:
```
E:\work\dotnet\MIEngine\build\DropFiles.targets(16,5): error MSB3030: Could not copy the file "E:\work\dotnet\MIEngine\bin\Debug\\Microsoft.MIDebugPackage.dll" because it was not found.
```

**Comment by gregg-miskelly** [comment]
@Dmitri-Botcharnikov did you try find-in-files (Ctrl+F in Visual Studio). I believe the line you will want to change is:

```
MIEngine\src\MIDebugPackage\MIDebugPackage.csproj(207):    <DropSignedFile Include="$(OutDir)\Microsoft.MIDebugPackage.dll" />
```

**Comment by Dmitri-Botcharnikov** [comment]
@gregg-miskelly: thank you for advice, I've searched for these settings in project's properties GUI in VS without success.

**Comment by gregg-miskelly** [comment]
@Dmitri-Botcharnikov sounds good. I will add this advice to the Wiki page.
