### ISSUE TITLE
Symbols not found when debugging

### ISSUE THREAD

**Issue by chaoticbob** [Microsoft/MIEngine#473]
When debugging a custom build of MIEngine that's launching a child Visual Studio to connect to GDB, if I set a breakpoint in MICommandFactory, I get a breakpoint warning that says, "The breakpoint will not currently be hit. No symbols have been loaded for this document." 

I have modified MICore to have a custom Asssembly name and have placed the resulting .dll and .pdb files into MIDebugPackage. And set the the action to "None" for the stock MICore .dll and .pbd. 

I'm wondering if the custom Assembly name is causing some issues for the debugger when it's looking for the symbols?

**UPDATE 1:**
I reverted to the stock MICore .dll and .pdb and am still not able to set a breakpoint in MICommandFactory.

**Comment by gregg-miskelly** [comment]
I don't have any good guess for why your breakpoint wouldn't be hitting unless somehow your code isn't getting invoked. You could adding a Debug.Assert or Debug.Break to force stopping at that location. You could also do a `dumpbin /headers <path-to-your-dll> | fiindstr RSDS` to verify that your dll is correctly building a PDB at the path you expect.

**Comment by chaoticbob** [comment]
Thanks for the response Greg. I figured out why this was happening and it was a totally silly mistake. My VSI component was referencing the GUID of the wrong debugger at launch time.
