### ISSUE TITLE
DebugEngineHost for private distrutibution through VSIX

### ISSUE THREAD

**Issue by seanshpark** [Microsoft/MIEngine#489]
When I build and debug run MIEngine inside VS2015, it works fine.
With the guide from [Redistribution](https://github.com/Microsoft/MIEngine/wiki/Redistribution) when I make a release version of VSIX and test, I get this error:
```
The debugger is not properly installed.  Cannot debug the requested type of code.  Run setup to install or repair the debugger.
```
I've found that inside of VSIX in Release folder, DebugEngineHost.dll is result from the DebugEngineHost.stub and it's a Contract dll.
How do I let the VS2015 not use this from stub but the one from DebugEngineHost project?
Should I unpack VSIX and replace the DLL and Zip it again?

**Comment by seanshpark** [comment]
CC @manu-silicon , @gregg-miskelly , @Dmitri-Botcharnikov

**Comment by gregg-miskelly** [comment]
@seanshpark my guess would be that one of the following two things is happening:

1. Some project is referencing the stub project without `<Private>false</Private>` ([example](https://github.com/Microsoft/MIEngine/blob/master/src/MICore/MICore.csproj#L115)).
2. The '[BuiltProjectOutputGroupDependencies](https://github.com/Microsoft/MIEngine/blob/master/src/MIDebugPackage/MIDebugPackage.csproj#L243)' is mistakenly including the stub assembly.

I would probably suggest checking the projects for 1, and if that doesn't work, comb through the verbose build logs to see what is dragging it in.

**Comment by seanshpark** [comment]
@gregg-miskelly , Thanks!. Found that `SSHDebugPS.csproj` did not have `<Private>false</Private>`. I'll prepare a patch.
