### ISSUE TITLE
Support for VS2017?

### ISSUE THREAD

**Issue by BerndBunk** [Microsoft/MIEngine#513]
Hello devs
VS2017 RC (former "v15") is public, and I wonder if/when there will be support for this in this MI Engine?
Is someone already working on this?
Regards,
Bernd

**Comment by gregg-miskelly** [comment]
@BerndBunk what support are you looking for? MIEngine ships in VS 2017, and the project should build in it.

**Comment by BerndBunk** [comment]
Yes, now I also found it.
What I am actually looking for is the source code for this MI Engine launch in VS2017.
I have a similar Debug Engine based on the same Sample Debug Engine code, and it fails to launch in VS2017. Can you give me a hint where to find this MI Engine launch? And if you had to adapt anything for VS2017 here?
Regards,
Bernd

**Comment by gregg-miskelly** [comment]
@BerndBunk Do you mean the command window code (Debug.MIDebugLaunch)? https://github.com/Microsoft/MIEngine/blob/master/src/MIDebugPackage/MIDebugPackagePackage.cs#L360

No, there were no changes there for 2017.

**Comment by Darker** [comment]
If it ships with visual studio 2017, how do I use it? I cannot find how to use it. I have a makefile project and I'd like to use MIEngine to debug with gdb.

**Comment by gregg-miskelly** [comment]
@Darker Do you mean you have some sort of unix-style makefile and you are on Windows using Visual Studio? If so, you would likely want to use the "Open Folder" support: https://blogs.msdn.microsoft.com/vcblog/2017/07/19/using-mingw-and-cygwin-with-visual-cpp-and-open-folder/

You can use that for both local (ex: mingw) and remote (ex: debugging code running on Linux).
