### ISSUE TITLE
LocalLaunchOptions example?

### ISSUE THREAD

**Issue by g40** [Microsoft/MIEngine#528]
2 questions:

Does anyone have a working example they can share?
How do you pass an initialization file to GDB. Can this be specified in the MIDebuggerPath attribute?

My dysfunctional example:

`<?xml version="1.0"?>
<LocalLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014" MIDebuggerPath="R:\src\cypress\fx3\debug\arm-none-eabi-gdb.exe" TargetArchitecture="arm" MIMode="gdb" ExePath="R:\src\cypress\fx3\GpifToUsb\Debug\GpifToUsb.elf">
                            </LocalLaunchOptions>`

When run this pops up a message claiming 'Launch options string provided by the project system is invalid. Data at the root level is invalid. Line 1, position 1'

TAIA.

**Comment by gregg-miskelly** [comment]
Example launch options are in https://github.com/Microsoft/MIEngine/blob/master/src/MICore/ExampleLaunchOptions.xml

There is also a schema file in the MICore project, and I would definitely recommend having that open in VS while editing.

The way that MIEngine expects you to use initialization files is to stop using initialization files and instead take the commands from the initialization file, and add those to the 'CustomLaunchSetupCommands'.

If your scenario really requires an initialization command you could either send in a PR to support that or point the MIDebuggerPath at a script that would start GDB with whatever arguments you want.

**Comment by g40** [comment]
Hello Gregg, 

Thanks for the quick reply. Silly of me to have missed the referenced XML file. 

I'm trying to invoke the debugger using a custom extension as mentioned here: https://github.com/Microsoft/MIEngine/issues/238#issuecomment-208801667. This invokes the debugger as shown below. Is this no longer best practice?

```
IVsDebugger4 debugger = (IVsDebugger4)GetService(typeof(IVsDebugger));
VsDebugTargetInfo4[] debugTargets = new VsDebugTargetInfo4[1];
debugTargets[0].dlo = (uint)DEBUG_LAUNCH_OPERATION.DLO_CreateProcess;
debugTargets[0].bstrExe = filePath;                      // fully qualified path to target
debugTargets[0].bstrOptions = xmlOptions;        // schema conformant XML options
// GUID from R:\src\vs\MIEngine\src\MIDebugEngine\AD7.Impl\EngineConstants.cs
debugTargets[0].guidLaunchDebugEngine = new Guid("{ea6637c6-17df-45b5-a183-0951c54243bc}");
VsDebugTargetProcessInfo[] processInfo = new VsDebugTargetProcessInfo[debugTargets.Length];
debugger.LaunchDebugTargets4(1, debugTargets, processInfo);
```

This system works correctly when passed PipeLaunchOptions.

TAIA.

**Comment by gregg-miskelly** [comment]
@g40 that looks correct. What error are you getting?

**Comment by g40** [comment]
Right now the best I have is here: https://github.com/Microsoft/MIEngine/issues/528#issue-198351284

Have not dug any further into MIE itself.

**Comment by g40** [comment]
Closing this one. Problem has moved along the food chain.
