### ISSUE TITLE
GetClrDbg.sh returned a non-zero code: 1

### ISSUE THREAD

**Issue by cstyle** [Microsoft/MIEngine#531]
I completely followed this [tutorial](https://docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images) to make the DotNet Core with Docker project.
However When I run the command with './dockerTask.sh build debug' , I have got an error at following point.

Step 5 : RUN curl -SL https://raw.githubusercontent.com/Microsoft/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh --output GetClrDbg.sh     && chmod 700 GetClrDbg.sh     && ./GetClrDbg.sh $CLRDBG_VERSION     && rm GetClrDbg.sh
 ---> Running in 049cb0e71b0a
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 15024  100 15024    0     0   1862      0  0:00:08  0:00:08 --:--:--  3318
Using arguments
    Version                    : 'VS2015U2'
    Location                   : ''
    SkipDownloads              : 'false'
    LaunchClrDbgAfter          : 'false'
    RemoveExistingOnUpgrade    : 'false'
Info: Using clrdbg version '15.0.26022.0'
Info: Previous installation at  not found
Error: Install location is not set
**ERROR: Service 'api' failed to build: The command '/bin/sh -c curl -SL https://raw.githubusercontent.com/Microsoft/MIEngine/getclrdbg-release/scripts/GetClrDbg.sh --output GetClrDbg.sh     && chmod 700 GetClrDbg.sh     && ./GetClrDbg.sh $CLRDBG_VERSION     && rm GetClrDbg.sh' returned a non-zero code: 1**
 
I have updated brew and dotnet core SDK.

![api_ _-bash_ _141x57_and_new_issue_ _microsoft_miengine](https://cloud.githubusercontent.com/assets/2171088/21963689/f13248ec-db79-11e6-8555-a158c7141099.jpg)

**Comment by rajkumar42** [comment]
@cstyle ./GetClrDbg.sh takes two parameters version and location. It looks like the location is missing and hence the failure. @weidazhao can you please take a look?

**Comment by ptoonen** [comment]
Issue seems to be on line 270, fixed in https://github.com/Microsoft/MIEngine/pull/533
