### ISSUE TITLE
Launch fails when using 'externalConsole' and path with spaces

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/MIEngine#543]
When MIEngine is placed in a directory with spaces on OSX, then launch requests that have 'externalConsole' enable fail.

This may be due to https://github.com/Microsoft/MIEngine/blob/master/src/MICore/TerminalLauncher.cs#L99 is not quoted and same for {4} at https://github.com/Microsoft/MIEngine/blob/master/src/MICore/UnixUtilities.cs#L58.

**Comment by DavidKarlas** [comment]
This can be closed since now I'm using 'runInTerminal' command hence I don't hit this problem anymore.

**Comment by gregg-miskelly** [comment]
Thanks!
