### ISSUE TITLE
Android debugging fails for API level 24+ apps on Andoird 7 devices

### ISSUE THREAD

**Issue by gregg-miskelly** [Microsoft/MIEngine#567]
Repro steps:
1. Create an NDK app targeting API level 24+
2. Use a Google Pixel or other Android 7 device
3. Hit F5 to start debugging

Result:
Error message with -- Unable to start debugging. Unexpected GDB output from command "-target-select remote:5039". Remote communication error. Target disconnected.: No error.

Work around:
Use chmod to mark the app's directory readable from the adb user -- `adb.exe shell run-as my-example-app "/system/bin/chmod a+x /data/data/my-example-app"`

**Comment by gregg-miskelly** [comment]
This fix should ship in the next full update to VS 2017.

**Comment by JonTerp** [comment]
I am still receiving this error on Android API level 24 apps in Visual Studio 2017 release "15.2".

For reference I am attempting to debug an APK generated by Unreal Engine 4 version 4.15.

**Comment by j0rg3n** [comment]
15.2 (26430.14) does not seem to contain the fix - debugging an API level 24 app on an HTC 10 device yields the exact error message above.

**Comment by gregg-miskelly** [comment]
The fix would be in 15.3

**Comment by eliodeberardinis** [comment]
Hi Gregg - I tried your workaround but I'm not sure I can follow/understand every step:

Use chmod to mark the app's directory readable from the adb user -- adb.exe shell run-as my-example-app "/system/bin/chmod a+x /data/data/my-example-app"

 It complains that the "Package is unknown"

Can you be just a little bit more specific on the steps? I have the .apk in a folder /my/folder/myApp.apk.

Thank you for any help! (unfortunately I can't upgrade to Visual Studio 2017 :-(

**Comment by gregg-miskelly** [comment]
@eliodeberardinis If you want, I _think_ you could build the MIEngine from source (I would use the Release configuration) and patch your VS 2015 copy with the current version.

https://github.com/Microsoft/MIEngine/wiki/Building-the-MIEngine
https://github.com/Microsoft/MIEngine/wiki/Patching-Visual-Studio

If that doesn't work, to try my work around you want to find the identity of your application, and replace 'my-example-app' with that. If you aren't sure what that is, or the paths, you can turn on [logging](https://github.com/Microsoft/MIEngine/wiki/Logging) and see what command MIEngine is trying to run to start debugging.

I hope this helps.

**Comment by eliodeberardinis** [comment]
This worked! Thank you very much.
The debugger cannot hit breakpoints though, suggesting it's missing a lot of .so files from /system/lib or system/vendor. Any Idea on how to solve that? I'm sure we built our APK in debug mode and I manually specified our .so symbols files. Any thoughts? (I know this is out of scope so don't worry too much).

**Comment by eliodeberardinis** [comment]
This worked. Thank you!
