### ISSUE TITLE
instruction pointer arrow missing in Disassembly window

### ISSUE THREAD

**Issue by digittigerw** [Microsoft/MIEngine#576]
Hi,

In our debugger based on MIEngine, in the Disassembly window, there is not yellow arrow pointing to the current instruction. Instead just the text caret is there as the indicator and moves properly while stepping, which means the PC value is correctly reported to the core debugger. 
So do you know how to get the yellow arrow to show up ?

Thanks !

**Comment by gregg-miskelly** [comment]
Are you seeing AD7DisassemblyStream.GetCodeLocationId called for the IDebugCodeContext2 which is the current instruction address?
Does the value returned from that match up with the right line in the disassembly as returned in `Read` via `prgDisassembly[iOp].uCodeLocationId`?

**Comment by digittigerw** [comment]
Ok, I figured it out and it's due to this bug in AD7Disassembly.cs.
Line 30:
     ppCodeContext = new AD7MemoryAddress(_engine, (uint)uCodeLocationId, null);

The cast of uCodeLocationId to "uint" is problematic for 64-bit target.  

Same problem with 
line 131
        _addr = (uint)uCodeLocationId;

Removing the casts fixed my problem.

**Comment by gregg-miskelly** [comment]
Excellent. Do you mind sending a PR?

**Comment by digittigerw** [comment]
I tried to create a pull request, but I don't have the privilege to push a branch to the repo.  What should I do for that ? or is it ok I just attach a patch here ?

**Comment by gregg-miskelly** [comment]
So we follow the 'GitHub fork model'. So you want to:
1. go to https://github.com/Microsoft/MIEngine and clone the repo into your account
2. Push your changes up to GitHub
3. Go to https://github.com/digittigerw/MIEngine/pulls and create a pull request for merging your changes into MIEngine master.

Here is some more general information on GitHub pull requests if this is the first time you have submitted one: https://help.github.com/articles/about-pull-requests/

It should be pretty easy. Thanks!

**Comment by gregg-miskelly** [comment]
Thanks for fixing this!
