### ISSUE TITLE
Debugging works for Launch but not Attach on Linux

### ISSUE THREAD

**Issue by jceddy** [Microsoft/MIEngine#599]
I have a project that I have been debugging on Linux using the MIEngine and clrdbg. When I launch the application from Visual Studio, the debugger attaches fine and my breakpoints are hit. If I run the application as a daemon started by the system, Visual Studio appears to let me attach the debugger to the process, but there is no output in the output window (besides the initial header explaining what I am allowed to do with the debugging tools), and none of my breakpoints are hit.

I am using VS2015 and using Debug.MIDebugLaunch in the Command Window either way. Here are what my Options Files look like...

For Launching the application from Visual Studio:
```
<?xml version="1.0" encoding="utf-8" ?>
<PipeLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
  PipePath="path-to\plink.exe" PipeArguments="-i path-to\ssh-debug.ppk user@machinename -batch -t ~/clrdbg/clrdbg --interpreter=mi"
  TargetArchitecture="x64" MIMode="clrdbg" ExePath="dotnet" WorkingDirectory="~/workingDirectory" ExeArguments="ApplicationName.dll">
</PipeLaunchOptions>
```

For Attaching to the running application from Visual Studio (I change the ProcessId if I restart the service and it comes up under a different ID):
```
<?xml version="1.0" encoding="utf-8" ?>
<PipeLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
  PipePath="path-to\plink.exe" PipeArguments="-i path-to\ssh-debug.ppk user@machinename -batch -t ~/clrdbg/clrdbg --interpreter=mi"
  TargetArchitecture="x64" MIMode="clrdbg" ProcessId="19036">
  <LaunchCompleteCommand>None</LaunchCompleteCommand>
</PipeLaunchOptions>
```

Any ideas about what might be happening, or what I'm missing?
Is this a bug, or do I perhaps need to update something?

**Comment by jceddy** [comment]
I changed my "attach" Options File to look like this:

```
<?xml version="1.0" encoding="utf-8" ?>
<PipeLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
  PipePath="path-to\plink.exe" PipeArguments="-i path-to\ssh-debug.ppk user@machinename -batch -t ~/clrdbg/clrdbg --interpreter=mi --attach 19036"
  TargetArchitecture="x64" MIMode="clrdbg">
  <LaunchCompleteCommand>None</LaunchCompleteCommand>
</PipeLaunchOptions>
```

And it works, but now I can't figure out how to detach the debugger without killing the process.

**Comment by gregg-miskelly** [comment]
@jceddy did you try Debug->Detach All? You may need to add this command back if you are using the Web profile.

Also, is it possible for you to upgrade to VS 2017? SSH support is built into 2017's attach to process dialog, and also, we are going to be making a change soon that will break this scenario in 2015.

**Comment by jceddy** [comment]
@gregg-miskelly Debug->Detach All is disabled when I launch the debugger this way (is there something I can do to re-enable it?)

I'll ask about upgrading to VS 2017, but it might be a challenge given the environment I'm working in here.

**Comment by jceddy** [comment]
All I really need, I think, is a way to send -target-detach from Visual Studio to detach the debugger...haven't figured out a way to do it yet, though.

**Comment by gregg-miskelly** [comment]
@jceddy Here are a few things you can try:

1: Install [Visual C++ for Linux Development](https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.VisualCforLinuxDevelopment). It has been a while since I tried this, but this will upgrade your MIEngine to a newer version. I think this will fix detach, and it _might_ light up the [SSH attach dialog](https://blogs.msdn.microsoft.com/visualstudioalm/2017/01/26/debugging-net-core-on-unix-over-ssh/) scenario.

-or-

2: You could try opening the command window, and running `Debug.MIDebugExec -target-detach`. This might blow up, but you can certainly try it.

**Comment by jceddy** [comment]
I've put in the request for moving up to VS2017. I definitely would like to be able to use it for updating to .NET Core 2.0 when it is released, so I'm crossing my fingers.

Meanwhile, Installing Visual C++ for Linux Development has fixed the issue and made it work correctly with the ProcessId attribute to PipeLaunchOptions, so it looks like I'm good for now, thanks, @gregg-miskelly !
