### ISSUE TITLE
Apply <DisplayString> automatically in natvis

### ISSUE THREAD

**Issue by AndrewBrianHall** [microsoft/MIEngine#6]
I get the need for the [Visualized View] sub-menu, esp. for arrays and the like. But why can't the <DisplayString> part be applied automatically? If you expand the main node it is already evaluated anyway:
- imageName                                        std::string
- [Visualized View]     0x8c27c8 "foo"

**Comment by Trass3r** [comment]
Can't it be done with some kind of timeout and/or just asynchronously?
DisplayString is crucial to get a quick overview of the structures.
For arrays you could limit the initial values to like 10 and provide a ... entry to expand further.

**Comment by gregg-miskelly** [comment]
We wouldn't want to just blanket enable all DisplayStrings and try and handle this with a timeout -- even if VS gives up blocking on GDB, it will still cause any subsequent GDB operations to need to wait for the first thing to finish before preceding.

I could imagine using a timeout to enable some subset of DisplayStrings which are super useful -- ex: the string value of a std::string.

**Comment by Trass3r** [comment]
btw in contrast to the original description I often don't even get anything when expanding a top-level node. The [Visualized View] row just shows {...}

**Comment by gregg-miskelly** [comment]
@Trass3r can you open a new issue for that since they seem different? Please include some sort of repro steps if you can.

**Comment by Trass3r** [comment]
To be closed?

**Comment by gregg-miskelly** [comment]
Sure. At this point it seems very unlikely that we would decide to change this.
