### ISSUE TITLE
Add Linux build support for MIEngine in cpptools

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/MIEngine#605]
Need to have prebuild run first before building MIDebugEngine and MICore

Suggested by Gregg: change BuildAndTest.Proj to detect Linux (Andrew says IsMonoRuntime check determines this already) and if so, just build prebuild.proj and the two projects . Currently it builds prebuild and the solution file.

**Comment by DanOlivier** [comment]
What exactly is the procedure to build this under say Ubuntu (17.04)?

**Comment by WardenGnaw** [comment]
You can now build `MIDebugEngine-Unix.sln` with .NET 5 SDK. This will build MICore, MIDebugEngine, and more.
