### ISSUE TITLE
Runtime error after updating

### ISSUE THREAD

**Issue by digittigerw** [microsoft/MIEngine#640]
I have my own vsix extension based on MIEngine, which has been working well. The last time we synced with this upstream GitHub repo was half year ago.  I just merged the latest from this repo to my repo. Everything builds fine, but at runtime when I start debugger I got error message like this:  
"Could not load file or assembly System.Reflection.TypeExtensions...".   
Please see enclosed screenshot for more. I'm using VS 2015.

I've spent quite some time on this but cannot figure out why.  I used ProcessMonitor and saw it did fail to find the  System.Reflection.TypeExtensions.dll in a bunch of folders. My knowledge is limited on where the assemblies are installed and how to configure the extension to locate them.

Thanks in advance for any pointers.
![assemblynotfound_20170710](https://user-images.githubusercontent.com/1380545/28043348-1e4679a0-6597-11e7-83bf-232bd94abadf.png)

**Comment by gregg-miskelly** [comment]
If you look in the modules window, you can see the directory of where VS is loading the MIEngine from. Do you see a System.Reflection.TypeExtensions.dll next to it?

If my memory serves me correctly, it should be added to the VSIX from here:
https://github.com/Microsoft/MIEngine/blob/87b587e0adc8e9de11416f0db9735792abebbe7b/src/RequiredNetFX46FacadeAssemblies.targets#L9

**Comment by digittigerw** [comment]
Right,  I don't see the DLLs listed in RequiredNetFX46FacadeAssemblies.targets being copied to the output folder where MICore.dll is located.  It seems because of the change made to the file RequiredNetFX46FacadeAssemblies.targets.    
Where should this "$(NuGetPackagesDirectory)" be ? Is it ".../MIEngine/src/packages/" ( I see "System.Reflection.TypeExtensions\4.0.0\lib\net46\System.Reflection.TypeExtensions.dll" there)  ?  What could be wrong in my configuration ? 
Thanks !

**Comment by digittigerw** [comment]
Ok, I figured it out. I need to import miengine.settings.targets in my extension project so that the changed RequiredNetFX46FacadeAssemblies.targets will work as desired.  
Thanks for the help.

**Comment by WardenGnaw** [comment]
Closing as resolved.
