### ISSUE TITLE
[VS] Add support for exceptions tool window

### ISSUE THREAD

**Issue by pieandcakes** [microsoft/MIEngine#644]
Support for breaking on all exceptions with c++. For gdb, the documentation shows that we need to have support for https://sourceware.org/gdb/onlinedocs/gdb/Set-Catchpoints.html#Set-Catchpoints . It doesn't look like there is an MI implementation for it.

**Comment by gregg-miskelly** [comment]
Fixed with https://github.com/microsoft/MIEngine/pull/1245
