### ISSUE TITLE
VS2017 version of offroad debugging document is lacking how to attach remote process

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Microsoft/MIEngine#648]
I found [the original document](https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio-Legacy-Instructions) has been marked as Legacy and [the new document](https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio) has been published.
However, new version document is lacking how to attach the remote process over ssh. The old version is described [here](https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio-Legacy-Instructions#attaching-to-a-process).

This is because I'd like to use another command (docker rsh or oc rsh) instead of ssh. It worked at VS2015. However, VS2017 doesn't work.

**Comment by gregg-miskelly** [comment]
@richardstanton is this possible to do currently?

**Comment by richardstanton** [comment]
Due to the changed debug engine (in VS 2017 15.3) the offroad attach scenario is not supported. We thought this was good enough since SSH attach can be done thru VS natively. Obviously this is not the case, so I am actively investigating what it will take to reenable this scenario.

**Comment by tanaka-takayoshi** [comment]
@richardstanton Thanks.
I'd like to clarify now the remote process attach with SSH in Visual Studio 2017 is not a scope of MIEngine but a scope of Visual Studio. Is this right? Is so, I should ask the Visual Studio team the detail.

**Comment by richardstanton** [comment]
Yes, what has happened is that Visual Studio used to use MIEngine for these scenarios until version 15.3. Then Visual Studio switched to using a new engine that uses the VS Code protocol instead of MI. I am part of the Visual Studio team that did this transition, so hopefully I can answer any questions you have.

**Comment by tanaka-takayoshi** [comment]
Great. Actually, I want to attach to a remote process running on docker. I can do this in Visual Studio 2015 and MIEngine offroad debugging with "docker rsh" or "oc rsh" command instead of "plink (ssh with putty)" command. I'd like to do the same thing in Visual Studio 2017. However, VS 2017 only support "ssh" command natively and I can't add or edit a connection type in remote attach process. I'm looking for the way to use "docker rsh" command instead of "ssh" in Visual Studio 2017... If there is any other place to discuss, please let me know.

**Comment by richardstanton** [comment]
Unfortunately right now it will only work in Visual Studio 2017 version 15.2 and older. We have a fix ready and are planning on shipping it with Visual Studio 2017 15.5. However until then you will need to use an older version of Visual Studio 2017 (15.0 for example) and follow the Legacy instructions.

**Comment by tanaka-takayoshi** [comment]
Thanks for your comment, but I found I can't build ASP.NET Core 2.0 app in Visual Studio 15.0. So I'll wait for the 15.5.

**Comment by tanaka-takayoshi** [comment]
@richardstanton Now VS 15.5 has been released as a preview. Is there any information about this issue?

**Comment by andrewcrawley** [comment]
This should work in 15.5 preview 1.  Here's the launch.json I set up to test it out:

```json
{
  "version": "0.2.0",
  "adapter": "e:\\programs\\putty\\plink.exe",
  "adapterArgs": "-i d:\\andrewcr.ppk andrew@andrewcr-lnx-1 -batch -T ~/.vs-debugger/vs2017u5/vsdbg --interpreter=vscode",
  "languageMappings": {
    "C#": {
      "languageId": "3F5162F8-07C6-11D3-9053-00C04FA302A1",
      "extensions": [ "*" ]
    }
  },
  "exceptionCategoryMappings": {
    "CLR": "449EC4CC-30D2-4032-9256-EE18EB41B62B",
    "MDA": "6ECE07A9-0EDE-45C4-8296-818D8FC401D4"
  },
  "configurations": [
    {
      "name": ".NET Core Attach",
      "type": "coreclr",
      "request": "attach",
      "processId": "93189"
    }
  ]
}
```

Note that as of 15.5, the correct version of vsdbg to use is now `vs2017u5` rather than `vs2017u1`.

**Comment by tanaka-takayoshi** [comment]
@andrewcrawley Thanks! It worked.
At this point, the remote debugger can start. However, Visual Studio failed to load symbols during setting breakpoints. I will update later if this is an issue.

**Comment by dknippel** [comment]
@andrewcrawley  thank you for the launch.json example.  However, when I attempt to launch in VS I get an error stating 'cannot find debug adapter 'coreclr'.  Do I need to explicitly install the 'coreclr' debug adapter somehow?  I am using Visual Studio Community v15.5.5

**Comment by VladimirAkopyan** [comment]
do i understand this correctly- MIENgine is no longer a separate extention but is now part of VS2017, however currnetly the best way to remotely debug on linux using vs2017 is to use a new in-built ssh connectivity functionality? 
I am asking because I am struggling to get the "native" vs2017 ssh connection to work, however VSCode and MIengine instructions work well. I reported the issue here: 
https://github.com/Microsoft/VSLinux/issues/132
But in general I am kind of confused what;s happening

**Comment by tanaka-takayoshi** [comment]
I'm closing this issue because I confirmed the remote debugging from Visual Studio to remote .NET Core process by following [this document](https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio) now. I confirmed with the latest stable version 15.7.2 and the latest preview version (15.8.0 preview 1.1).
@VladimirAkopyan , I think your issue is slightly different from my reported issue. I was focusing on the lacking of documentation and it works now. Could you create a new issue specific for your issue? Or if you think your issue is as same as this case, could you reopen the case?

**Comment by ZoeShaw101** [comment]
@VladimirAkopyan same here, working on get the native vs2017 ssh coonection to work to luanch the process in docker, but there's problem: the debugger cannot find the program path, while the path is definitely correct, dont' know why?
