### ISSUE TITLE
how vscode v8protocol json data parsing to gdb command?

### ISSUE THREAD

**Issue by gufuguang** [Microsoft/MIEngine#702]
whether the  'Visual Studio Core Debugger'  is open source?  where to find the source code? I need add watchpoint function.

**Comment by gregg-miskelly** [comment]
Can you explain what you are trying to debug in more detail -- what is your scenario? If possible, what module are you talking about? Etc.

**Comment by gufuguang** [comment]
I use gdb debug stm32 application,  via gdb can set watchpoint function, but vscode don't have watchpoint function,  I want to try add watchpoint function to vscode.

**Comment by pieandcakes** [comment]
@gufuguang We added OpenDebugAD7 to this project which does translation from VS Code Protocol (aka OpenDebug) to AD7, which the rest of MIEngine uses to then communicate with gdb. Hopefully this will help you debug the overall process with VS Code.
