### ISSUE TITLE
Alpine 3.6 support

### ISSUE THREAD

**Issue by gighen76** [Microsoft/MIEngine#707]
I'm trying to install MIEngine on Alpine 3.6 using the following command

`curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v vs2017u5 -l ~/vsdbg`

It seems that isn't working: vsdbg command isn't recognized as executable. I've tried to install libc6-compat package and that errors occurred:
```
- Error relocating /vsdbg/libvsbaseservices.so: __isnanf: symbol not found
- Error relocating /vsdbg/libvsbaseservices.so: __finite: symbol not found
- Error relocating /vsdbg/libvsbaseservices.so: __finitef: symbol not found
- Error relocating /vsdbg/libvsbaseservices.so: __isnan: symbol not found
```

**Comment by gregg-miskelly** [comment]
@gighen76 You said MIEngine, but I think you actually mean vsdbg. Correct?

VSDbg doesn't yet support Alpine. I opened https://github.com/OmniSharp/omnisharp-vscode/issues/2165 to track that feature.

**Comment by gighen76** [comment]
That's correct. Thank you.
