### ISSUE TITLE
Natvis support 

### ISSUE THREAD

**Issue by digittigerw** [Microsoft/MIEngine#709]
Hi,  will Miscrosoft Natvis (https://msdn.microsoft.com/en-us/library/jj620914.aspx?f=255&MSPPError=-2147217396) work with or is it possible to be supported by GDB through this MIEngine ?  Thanks.

**Comment by gregg-miskelly** [comment]
The MIEngine has a partial implementation of natvis -- https://github.com/Microsoft/MIEngine/tree/master/src/MIDebugEngine/Natvis.Impl

In the regular C++ VS debugger, the C++ expression evaluator (EE) is owned by the Visual Studio team and therefore it can support the entirety of natvis, and it can optimize the C++ EE to make it fast.

In MIEngine, natvis has to be built on top of the GDB EE, so things don't work quite as well. But there are still pretty good chunks of natvis that can be implemented, and are fast enough to provide value.

**Comment by digittigerw** [comment]
Ha, good to know. Thanks !
