### ISSUE TITLE
Support ',<number>' to visualize a pointer as an array

### ISSUE THREAD

**Issue by digittigerw** [microsoft/MIEngine#715]
Hi, with a VC++ project in VS, if I have a pointer like this:
   int *myArr = new int[20];

I can watch the pointer "myArr" as an array in "Watch" windows, namely if I enter "myArr,2", it will show "myArr" as an array of int[2] like below
![image](https://user-images.githubusercontent.com/1380545/39414838-bbde1852-4c01-11e8-896f-4aea48855719.png)

With my MIEngine debugger, that does not work. So my question it, is there a way to do that with MIEngine ? Or is there a workaround ? 
Thanks !

**Comment by gregg-miskelly** [comment]
CC @WardenGnaw

**Comment by gregg-miskelly** [comment]
@digittigerw I believe you would evaluate something like `(int[20])myArr`.

@WardenGnaw do I have that right?

**Comment by digittigerw** [comment]
Yeah, actually (int[20])*myArr  works.  Thanks for the help ! @WardenGnaw @gregg-miskelly

**Comment by gregg-miskelly** [comment]
@digittigerw Excellent. I will leave this open to track the possible future feature of supporting ',<number>'.

**Comment by digittigerw** [comment]
@gregg-miskelly Cool. I'm really curious, can we add that support in MIEngine ? is interpretation (parsing) of the watch expression done by VS debugger engine or by debugger extension like MIEngine ?  
Issue #709 is my other more general question related to this.

**Comment by gregg-miskelly** [comment]
The MIEngine has a tiny bit of support for format specifier today. I think the only thing we implemented was `,x` and `,d`. The array size format specifier could be implemented using this code: https://github.com/Microsoft/MIEngine/blob/72df3ee1ad81a9698a35ced2410016ea9910c5e0/src/MIDebugEngine/Natvis.Impl/Natvis.cs#L501

**Comment by Trass3r** [comment]
https://github.com/microsoft/MIEngine/blob/62b1e7055ae0f84dd7332eb0699e352aa42d8d69/src/MIDebugEngine/Engine.Impl/Variables.cs#L344-L364

**Comment by Trass3r** [comment]
https://github.com/microsoft/MIEngine/blob/4f41195b4e9eaf04f8ce6f6af69dfa5443c95003/src/MIDebugEngine/Engine.Impl/Variables.cs#L430-L438

We could actually use the `*array@(len)` [syntax](https://sourceware.org/gdb/onlinedocs/gdb/Arrays.html) to make it work.

**Comment by WardenGnaw** [comment]
Addressed with:
https://github.com/microsoft/MIEngine/pull/1329
https://github.com/microsoft/MIEngine/pull/1345
