### ISSUE TITLE
Pdb not found / mismatch so I can't debug

### ISSUE THREAD

**Issue by Meai** [Microsoft/MIEngine#743]
.NET Core 2.1.301 (Both windows and linux)
VS 15.7.4
Yes, I use `<DebugType>portable</DebugType>`

Command used:

> >Debug.MIDebugLaunch /Executable:"C:/Users/pc/Desktop/shared_linux_vm_folder/ConsoleApp1/Linux_MyApp/bin/Debug/netcoreapp2.1/Linux_MyApp.dll" /OptionsFile:"C:/Users/pc/Desktop/shared_linux_vm_folder/ConsoleApp1/Linux_MyApp/options.xml"

Output Window:

> Using arguments
>     Version                    : 'vs2015u2'
>     Location                   : '/home/pc/.vs-debugger/vs2015u2'
>     SkipDownloads              : 'true'
>     LaunchClrDbgAfter          : 'true'
>     RemoveExistingOnUpgrade    : 'false'
> Info: Using clrdbg version '15.0.26022.0'
> Info: Last installed version of clrdbg is '15.0.26022.0'
> Info: ClrDbg is upto date
> Info: Skipping downloads
> Info: Launching clrdbg
> Loaded '/home/pc/workarea/software/dotnet/shared/Microsoft.NETCore.App/2.1.1/System.Private.CoreLib.dll'. Cannot find or open the symbol file.
> Loaded '/mnt/hgfs/shared_linux_vm_folder/ConsoleApp1/Linux_MyApp/bin/Debug/netcoreapp2.1/Linux_MyApp.dll'. Cannot find or open the symbol file.
> Loaded '/home/pc/workarea/software/dotnet/shared/Microsoft.NETCore.App/2.1.1/System.Runtime.dll'. Cannot find or open the symbol file.
> Loaded '/home/pc/workarea/software/dotnet/shared/Microsoft.NETCore.App/2.1.1/System.Runtime.Extensions.dll'. Cannot find or open the symbol file.
> Loaded '/home/pc/workarea/software/dotnet/shared/Microsoft.NETCore.App/2.1.1/System.Console.dll'. Cannot find or open the symbol file.
> Loaded '/home/pc/workarea/software/dotnet/shared/Microsoft.NETCore.App/2.1.1/System.Threading.dll'. Cannot find or open the symbol file.
> Hello World!
> The program '' has exited with code 0 (0x0).

As you can see, it says: "Linux_MyApp.dll'. Cannot find or open the symbol file."
To diagnose this I dumpbin'ed the .dll headers out and it shows a windows path to the pdb, but even when I compile on linux (which then uses a windows path) it still wont find the pdb so it must be a mismatch of the pdb internal guid(?) or something, I'm not sure how to diagnose this any further, much less fix it.
I also tried enabling logging with `Debug.MIDebugLog  /On /OutputWindow` but it shows no further error messages or relevant info.

Weird: I can attach and the symbols will be loaded if I start the app on linux first manually and then attach to it via visual studio. Of course this is too cumbersome to constantly do manually.
It does say though "Breakpoint warning: A copy of C:\Users\pc\Desktop\shared_linux_vm_folder\ConsoleApp1\Linux_MyApp\Program.cs was found in Linux_MyApp.dll, but the current source code is different from the version built into Linux_MyApp.dll." which shouldnt be the case either.

**Comment by gregg-miskelly** [comment]
@Meai clrdbg is no longer being maintained, and will not work correctly with .NET Core 2.1 applications. You want to switch over to using vsdbg. Instructions: https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio
