### ISSUE TITLE
TcpLaunchOptions - Hang on Debugging Start

### ISSUE THREAD

**Issue by ezolotko** [Microsoft/MIEngine#755]
I am trying to use GDB remote debugging via TCP by providing the following options:
<TcpLaunchOptions xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014" Hostname="localhost" Port="1234" />

With the server started like this:
gdbserver localhost:1234 a.exe

However, the MIEngine hangs while establishing connection to the server. This happens when I am using the following command from VS:
Debug.MIDebugLaunch /Executable:".." /OptionsFile:"..."
or invoking the engine programmatically from my own code.
Maybe my server setup is wrong, could you please help with how to start debugging remote targets using TCP (or SSH) with the latest MI engine?

**Comment by paulmaybee** [comment]
This should be possible. Have you specified the MIDebuggerServerAddress to be "localhost:1234" in your options file? What does your options file look like?

**Comment by ezolotko** [comment]
Thank you for your answer, the following options file worked:

<LocalLaunchOptions
    xmlns="http://schemas.microsoft.com/vstudio/MDDDebuggerOptions/2014"
    MIDebuggerPath="gdb.exe"
    MIDebuggerServerAddress="localhost:1234">

I tried to use TcpLaunchOptions instead, and it didn't work. Thank you again.
