### ISSUE TITLE
Linux folder structure not consistent

### ISSUE THREAD

**Issue by illikovegae** [Microsoft/MIEngine#791]
Hi,

Using latest VS2017 and 'empty linux project' I notice the folder structure created on the remote linux host is not very consistent.

### Example 1:
Windows side folder structure example:
```
mylib\somefile.cpp
myproject\myproject.sln
myproject\myproject.vcxproj
myproject\myproject.vcxproj.filters
myproject\myproject.vcxproj.user
```
 
Vcxproj:
![image](https://user-images.githubusercontent.com/43888453/47212891-bbdbc780-d399-11e8-84b9-e65a75ae3d48.png)
 
Note : the filter mylib contains somefile.cpp. There is no file in "myproject (Linux)".
 
On the linux side, somefile.cpp will be put at the root of the project folder:
```
redacted@redactedPC:~/projects/myproject$ pwd
/home/redacted/projects/myproject
redacted@redactedPC:~/projects/myproject$ ls -l
total 0
-rw-rw-r-- 1 redacted redacted 10 Oct 19 12:04 somefile.cpp
```
 
### Example 2:
 
Same as example 1 but I add a file in "myproject (Linux)":
Windows side folder structure example:
```
mylib\somefile.cpp
myproject\myproject.sln
myproject\myproject.vcxproj
myproject\myproject.vcxproj.filters
myproject\myproject.vcxproj.user
myproject\newfile.cpp
```
 
Vcxproj:
![image](https://user-images.githubusercontent.com/43888453/47212865-a797ca80-d399-11e8-92ba-2053e357be12.png)

On linux, delete everything on myproject:
`$ rm -rf myproject/`
 
Then Rebuild all on Visual Studio.
After copying files, the structure on linux is completely different: mylib and myproject folders will be created. It will look like the same structure as on the windows side:
 
```
redacted@redactedPC:~/projects/myproject$ ls -lisaR
.:
total 4
 4503599628030243 0 drwxrwxr-x 0 redacted redacted 512 Oct 19 12:16 .
59954170039372370 4 drwxrwxr-x 0 redacted redacted 512 Oct 19 12:16 ..
 1688849861461688 0 drwxrwxr-x 0 redacted redacted 512 Oct 19 12:16 mylib
 3377699721724356 0 drwxrwxr-x 0 redacted redacted 512 Oct 19 12:16 myproject 
./mylib:
total 0
1688849861461688 0 drwxrwxr-x 0 redacted redacted 512 Oct 19 12:16 .
4503599628030243 0 drwxrwxr-x 0 redacted redacted 512 Oct 19 12:16 ..
1125899908040378 0 -rw-rw-r-- 1 redacted redacted  10 Oct 19 12:16 somefile.cpp 
./myproject:
total 0
3377699721724356 0 drwxrwxr-x 0 redacted redacted 512 Oct 19 12:16 .
4503599628030243 0 drwxrwxr-x 0 redacted redacted 512 Oct 19 12:16 ..
1407374884751029 0 -rw-rw-r-- 1 redacted redacted   9 Oct 19 12:16 newfile.cpp
```

Is it expected ?
The issue I see here is that this has an impact in the INCLUDE directories. On some cases, if you want to include headers located in the folder mylib, you will have to use -I../mylib/

Is that a bug ?
I attached an example folder struture with the 'myproject' vxcxproj used here

Thanks !

[vs2017_example.zip](https://github.com/Microsoft/MIEngine/files/2495434/vs2017_example.zip)

**Comment by gregg-miskelly** [comment]
This repo doesn't really have anything to do with the way files are deployed, so you might be better off using 'Help->Send Feedback->Report a problem' from Visual Studio.

That said, I will see if I can forward this to a C++ project system developer to help.

**Comment by illikovegae** [comment]
thanks, let me know if I should still send this bug through the VS report system

**Comment by illikovegae** [comment]
I added a visual studio issue here https://developercommunity.visualstudio.com/content/problem/378479/linux-folder-structure-not-consistent.html
