### ISSUE TITLE
Debugging a file with multiple static anonymous structs show the members of the first one in all of them

### ISSUE THREAD

**Issue by spidey** [microsoft/MIEngine#812]
Sorry for the confusing title, couldn't think of a better name. Let me try to explain it with more words. These are the conditions:
- Source code with multiple anonymous structs. In my case I only have two. They are both static initialized.
- Add a watch expression for each of them.
- Debug a function in this module and check the watch.
- Both structures have the same members on the watch interface, but the second one shows corrupt data, since the types doesn't match.

Trying to watch a specific member of the second struct also gives an error.

![image](https://user-images.githubusercontent.com/696327/49383778-b0055400-f700-11e8-9d7e-811325be5914.png)

It seems that all anonymous structs get the same internal name and only the first actually get used during debugging.

**Comment by pieandcakes** [comment]
Same as #820.

**Comment by spidey** [comment]
Sorry for not being able to contribute with sample code. Thanks for closing the issue, anyway.

**Comment by pieandcakes** [comment]
@spidey Can you look at the PR related to #820 and see if that fix will work for your case?
