### ISSUE TITLE
[VSCode] Implement UseForBreakpoints for sourceFileMap with the C++ extension

### ISSUE THREAD

**Issue by mobad** [microsoft/MIEngine#819]
This is kind of two issues...
The first is that when using GDB and setting a breakpoint on a file which has the same name as another file it will set the breakpoint on the wrong one.
For example:
a/file.cpp
b/file.cpp
set breakpoint on b/file.cpp and it gets set on a/file.cpp
(2854) <-1272-break-insert -f file.cpp:123
This still seems like the open issue https://github.com/Microsoft/MIEngine/issues/147

That issue mentions that a sourceFileMap might fix this and looking at MapCurrentSrcToCompileTimeSrc it seems like it _should_ but you need to enable the undocumented "useForBreakpoints" flag.

Looking at the format defined in https://github.com/Microsoft/MIEngine/blob/master/src/MIDebugPackage/OpenFolderSchema.json
It seems like I should just need to add:
`            "sourceFileMap": {
                "/compiler/path": {
                    "editorPath": "/editor/path",
                    "useForBreakpoints": true
                }
            },`

But I now get the error:
`ERROR: Configuration for 'sourceFileMap' has a format error and will be ignored.
Exception: Error reading string. Unexpected token: StartObject. Path '/compiler/path'.`

Looking at SetCommonDebugSettings it looks like it's only parsing it as a string, not an object.

Is there any other fix/workaround to get debugging working with the same file names with GDB?

**Comment by pieandcakes** [comment]
@mobad Which version of Visual Studio are you trying this in? Can you give me the full version information?

**Comment by mobad** [comment]
This was with 1.30.1 of vscode with 0.20.1 of vscode-cpptools

**Comment by pieandcakes** [comment]
@mobad That has not been enabled in the VS Code extension. Theres work that needs to be done in OpenDebugAD7 to switch to using MIEngine to do the `launch.json` parsing. Currently in this repo there are two implementations of SourceFileMapping.

**Comment by pieandcakes** [comment]
i have marked it as a feature request and updated the title.

**Comment by RYDB3RG** [comment]
@pieandcakes I was wondering if removing this line would help:
https://github.com/microsoft/MIEngine/blob/3e998f58181d99315c85498cac483ee800e38ac6/src/MIDebugEngine/Engine.Impl/Breakpoints.cs#L117

I think its the reason that a fully qualified name becomes its basename and thus leads to multiple breakpoints

**Comment by pieandcakes** [comment]
@RYDB3RG The reason that was done is to support paths that don't exactly match. The work needs to be done in `OpenDebugAD7` to support the `useForBreakpoints` or forward the entire json blob to `MIEngine` (where you referenced the code above) so that the json parser there handles the setting.
