### ISSUE TITLE
Entire struct not displayed in debugger

### ISSUE THREAD

**Issue by cakeray** [microsoft/MIEngine#820]
Working with the glm library, struct contents are being partially displayed by gdb. This is a gist of what glm::tvec2 looks like..
```
template<typename T>
struct tvec2
{
    union {T x, r, s;};
    union {T y, g, t;};
}
```

This is what is shown in the debugger...
![locals](https://user-images.githubusercontent.com/22112595/50921786-b670a500-13fd-11e9-90a3-bf8c1f21706c.jpeg)

My launch.json file is
```
"version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) App",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceRoot}/build/<app_name>",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "linux": {
                "MIMode": "gdb",
                "miDebuggerPath": "/usr/bin/gdb",
                "setupCommands": [
                    {
                        "description": "Enable pretty-printing for gdb",
                        "text": "-enable-pretty-printing",
                        "ignoreFailures": true
                    }
                ]
            }
        }
    ]
```
Here are my system details:
```
Ubuntu 18.04
gcc v7.3.0
gdb v8.1.0
VSCode 1.30.2
ms-vscode.cpptools v0.20.1
```

How do I get the debugger to display the entire contents of the struct? In the image shown, minEdgePoint and maxEdgePoint do not display the union with y,g,t values.

**Comment by puscas** [comment]
Hi!

I have the same issue, did you found a solution for it?

My setup is:
Ubuntu 18.04.1 LTS
gcc v7.3.0
gdb v8.1.0.20180409
VSCode v1.30.2
ms-vscode.cpptools v0.20.1

**Comment by puscas** [comment]
I noted the Natvis is sending an error when I open the structure in debug:

 Natvis failed to parse typename: union {...}

**Comment by cakeray** [comment]
@puscas I haven't found a solution for it yet, I'm hoping someone here knows why this is happening.
Where do you see the Natvis error?

**Comment by pieandcakes** [comment]
@puscas If you are using a `natvis` can you provide it? If you are not, let me know too as the `natvis` parsing shouldn't be doing anything. 

Also if you can provide a small application I can use to repro this, that would help me investigate this quickly.

**Comment by puscas** [comment]
@cakeray I see the error when I put a break point to see the values of the ::glm::vec3 and in the "variables" panel, opening the ::glm::vec3 variable triggers the message in the "debug console" panel. It's necessary to enable the "engineLogging" in launch.json to see it.

@pieandcakes I'm just using the Visual Code as is, I didn't tweaked or changed anything.
The launch.json:
`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/a.out",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "externalConsole": false,
            "linux": {
                "logging": {
                    "engineLogging": true,
                },
            }
        }
    ]
}`

The sample cpp code:
`#include <glm/vec2.hpp>
#include <stdio.h>

int main (int argc, char** argv) {
	glm::vec2 v {1, 2};
	printf("%f %f", v[0], v[1]); // Set a breakpoint here
	return 0;
}`

**Comment by cakeray** [comment]
@puscas Thanks. I followed your steps and I'm seeing the same Natvis error...
"Nativs failed to parse typename: union {...}"

**Comment by pieandcakes** [comment]
@cakeray I need to investigate. This is on my list of items to look at when I have a free moment. The easier it is to repro, the quicker I can investigate. If you have a small project that I can download that simulates this issue, I'll be able to fix it faster. I think @puscas provided an example but i'll need to figure out where to pull in the `glm` libraries from.

**Comment by pieandcakes** [comment]
This (the struct not expanding) looks like a VS Code issue. I opened https://github.com/Microsoft/vscode/issues/67624 on their page for it.

For the `Natvis failed to parse`, if you can give me a small app that I can repro it, I'll investigate further, but with my quick and dirty example in the VS Code bug I don't see that error.

**Comment by cakeray** [comment]
I can work on a simple code file if required but the quick and easy example @puscas provided should be good enough to see the issue.

I see the `Natvis failed to parse` error only when engine logging is set. For the engineLogging log should I just go ahead and Copy+Paste all from Debug Console or is there a log file generated that I don't know about?

**Comment by cakeray** [comment]
@pieandcakes Just wanted to follow up on this issue. I've been keeping an eye on the linked VS Code issue as well to see how it progresses along. Is there any work around to this? I work with structs like this every single day, so right now I'm using "-exec print" to view all the values and it can get a bit tedious.

**Comment by gregg-miskelly** [comment]
If you have control over the definition of the struct: the work around would be to change the field names so that all are unique.

**Comment by pieandcakes** [comment]
https://github.com/microsoft/MIEngine/pull/873

**Comment by pieandcakes** [comment]
This is now in vscode-cpptools version `0.24.0-insiders`

**Comment by MStachowicz** [comment]
@pieandcakes I am getting this error using the GLM natvis file provided inside the glm repo. I appreciate this is closed and from 2019 but its the most relevant and only exact result online for this issue.

I am launching via the below launch.json using the GDB debugger and the Cmake extension.

**Version/Extension:**
```
VScode v1.94.2
C/C++ v1.22.9
CMake v0.0.17
CMake Tools v1.19.52
```

**launch.json:**
```
{
	"version": "0.2.0",
	"configurations": [
            {
			"name": "(gdb) Launch",
			"type": "cppdbg",
			"request": "launch",
			"program": "${command:cmake.launchTargetPath}", // Resolved by CMake Tools:
			"args": [],
			"stopAtEntry": false,
			"cwd": "${workspaceFolder}",
			"environment": [ { "name": "PATH", "value": "${env:PATH}:${command:cmake.getLaunchTargetDirectory}" } ],
			"externalConsole": true,
			"MIMode": "gdb",
			"logging": { "natvisDiagnostics": "verbose", },
			"visualizerFile": "${workspaceFolder}/.vscode/glm.natvis",
			"showDisplayString": true,
			"setupCommands": [
				{
					"description": "Enable pretty-printing for gdb",
					"text": "-enable-pretty-printing",
					"ignoreFailures": true
				}
			]
		}
	]
}
```

I can provide the GLM natvis but its as-provided in the repo [here](https://github.com/g-truc/glm/blob/33b4a621a697a305bc3a7610d290677b96beb181/util/glm.natvis)


Debug console in VS prints below when I expand a vec3:
```
[Natvis] [Error] Natvis failed to parse typename: union {...}
[Natvis] [Error] Natvis failed to parse typename: union {...}
[Natvis] [Error] Natvis failed to parse typename: union {...}
```
