### ISSUE TITLE
natvis collections only show the first 50 elements

### ISSUE THREAD

**Issue by paulmaybee** [microsoft/MIEngine#821]
It is not possible to view elements beyond the first 50, regarless of size of the collection.

**Comment by Trass3r** [comment]
See microsoft/vscode-cpptools#4843.

**Comment by FDCTLC** [comment]
Hello, is there any update on this topic?
Best regards

**Comment by WardenGnaw** [comment]
Fixed in https://github.com/microsoft/MIEngine/pull/1333
