### ISSUE TITLE
build master head with VS 2019

### ISSUE THREAD

**Issue by digittigerw** [microsoft/MIEngine#842]
Hi, is head of master branch supposed to build with VS 2019 preview ? I tried to build MICore  and ran into such error:
_Could not copy the file "obj\Debug\Microsoft.MICore.dll" because it was not found._

No such problem when build with VS 2017.

Thanks  for help !

**Comment by gregg-miskelly** [comment]
Yes, it should work. What solution configuration are you using? Do you get any errors/warnings before that?

**Comment by pieandcakes** [comment]
@digittigerw Please reopen/comment if it is still not working.
