### ISSUE TITLE
Use NuGet's V3 API during build

### ISSUE THREAD

**Issue by skofman1** [Microsoft/MIEngine#849]
I see in you [NuGet.config](https://github.com/Microsoft/MIEngine/blob/29c6569861b2042c43f04d8d78b2566db2e2ef1f/tools/NuGet/NuGet.config) that you are still using NuGet's V2 API. 
We strongly recommend moving to V3 API as it provides more reliable builds and [security improvements](https://blog.nuget.org/20180810/Introducing-Repository-Signatures.html).

The change is super simple:
Replace `https://www.nuget.org/api/v2/` with `https://api.nuget.org/v3/index.json`

**Comment by gregg-miskelly** [comment]
I think nothing is using this file and it should just be deleted.
