### ISSUE TITLE
Binary support for variable format

### ISSUE THREAD

**Issue by calliopemg** [microsoft/MIEngine#858]
I've seen people asking for support for this a lot (at least in the VSCode C/C++ extension issues). It seems as though it would be as simple as adding a case for ,t in the function linked below and using "binary" as the format, as that is a recognized format by -var-set-format. Am I wrong about this?

If it is actually this simple, maybe it would make sense to add the natural and decimal options too just because they're there. 

https://github.com/microsoft/MIEngine/blob/f4321d5731036780f20e4044ceba95412fd7482d/src/MIDebugEngine/Engine.Impl/Variables.cs#L343

**Comment by pieandcakes** [comment]
For Reference: 
*GDB/MI document for -var-set-format*
https://sourceware.org/gdb/onlinedocs/gdb/GDB_002fMI-Variable-Objects.html#GDB_002fMI-Variable-Objects

*GDB Format document* 
http://www.delorie.com/gnu/docs/gdb/gdb_55.html

**Comment by WardenGnaw** [comment]
Fixed with https://github.com/microsoft/MIEngine/pull/1031

You can use `,b` or `,bb` to get binary format.
