### ISSUE TITLE
Building MIEngine in Jan 2020 will fail due because of version number exceeding USHRT_MAX

### ISSUE THREAD

**Issue by WardenGnaw** [microsoft/MIEngine#865]
When Jan 2020 hits, MIEngine will have a version number in the range of 70000+ which is greater than 65535 when it is built. 

When updating the version number, be sure to notify partner teams (e.g. C++ IoT) with the version number change.

**Comment by gregg-miskelly** [comment]
Or change the file version, but not the assembly version...
