### ISSUE TITLE
VSDBG for arm64 platform

### ISSUE THREAD

**Issue by blackchoey** [microsoft/MIEngine#898]
DotNet 3.0 preview has already supported arm64. Could anyone help share where can I get the vsdbg for arm64 platform? The `https://aka.ms/getvsdbgsh` script doesn't work with arm64. Thank you!

**Comment by gregg-miskelly** [comment]
There isn't one available yet. Actually, even though there are 3.0 runtimes available for arm64, the debugging support for them still has problems. So both the VS debugger team and the .NET runtime team are working together to try and get this done. You can watch https://github.com/OmniSharp/omnisharp-vscode/issues/2105 for announcements once things are far enough along to try.
