### ISSUE TITLE
Cannot connect to containers based on mcr.microsoft.com/dotnet/core/aspnet:3.0 with VS2019 remote debug - error 0x80004005

### ISSUE THREAD

**Issue by MichaelSimons** [microsoft/MIEngine#948]
_Copied from https://github.com/dotnet/dotnet-docker/issues/1530 by @ktos_

## Steps to reproduce the issue
1. Create a new container where base image is `mcr.microsoft.com/dotnet/core/aspnet:3.0` or `mcr.microsoft.com/dotnet/core/aspnet:3.1` (or probably older, haven't tested) on a remote Docker host,
2. Try to connect to process using remote debug in VS2019 16.4.10,
3. Error: `Operation not supported. Unknown error: 0x80004005.`

## Expected behavior
List of processes to be attached to appears.

## Actual behavior

An error similar to this:

```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to connect to 'temperaturektosdev_temperatureservice3_1;ssh=ktos@[redacted]'.  Operation not supported. Unknown error: 0x80004005.
---------------------------
OK   
---------------------------
```

![](https://user-images.githubusercontent.com/1633261/70851877-41beaa00-1e9b-11ea-8666-d3f6be86a342.png)

## Additional information (e.g. issue happens only occasionally)

Described the whole problem in Microsoft/DockerTools#222, especially https://github.com/microsoft/DockerTools/issues/222#issuecomment-565748326 - everything is because the lack of `ps` program in the image. Installing it via `apt install procps` fixes the issue.

Problem appears only in **Buster** images, at least not in **Alpine** (there is `ps` installed, I confirmed).

Still not sure why it works flawlessly for my LOCAL Docker host (Windows) and not for my REMOTE Docker host (Ubuntu). Maybe there is some difference in getting processes info?

However, **I think that `ps` should be a part of a base image for ASP.NET Core web apps.**

## Output of `docker version`

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Fri Aug 16 14:20:06 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Wed Aug 14 19:41:23 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

## Output of `docker info`

```
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 21
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version:
runc version: N/A
init version: v0.18.0 (expected: fec3683b971d9c3ef73f284f176672c44b448662)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.15.0-72-generic
Operating System: Ubuntu 18.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.9GiB
Name: lisa.srv.kilibar.be
ID: PB2S:CT6S:MXWC:RGDU:YPLJ:5AJR:G266:UKX6:2LPL:UZ42:HBU4:7BOW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

_Copied from https://github.com/dotnet/dotnet-docker/issues/1530#issuecomment-566730278 by @MichaelSimons_

@ktos - in https://github.com/microsoft/DockerTools/issues/222 you said:

>Even more strangely, every other container on the same remote host allows me to be debugged, except every ASP.NET Core ones!

Can you share details about these other containers?  What technologies are they based on?  What base OS are the based on?

_Copied from https://github.com/dotnet/dotnet-docker/issues/1530#issuecomment-566771461 by @ktos_

@MichaelSimons:

> Can you share details about these other containers? What technologies are they based on? What base OS are the based on?

Of course.
It seems I overstated "every". Containers I can successfully connect to show list of processes available to debug are:

* registry:2.7 (https://hub.docker.com/_/registry, https://github.com/docker/distribution-library-image/blob/master/Dockerfile.noarch, based on Alpine),
* couchdb:latest (https://github.com/apache/couchdb-docker/blob/3bcc626d30623789b4750d076f059bcd010c2a04/2.3.1/Dockerfile - based on Debian Stretch, but `ps` is in that image),
* my own ktos/eleia:latest (https://github.com/ktos/Eleia/blob/master/Dockerfile - based on mcr.microsoft.com/dotnet/core/runtime:3.0-alpine).

Containers throwing error 0x80004005 in VS:
* jc21/registry-ui (based on https://hub.docker.com/r/jc21/node/dockerfile, based probably on https://github.com/nodejs/docker-node/blob/f5875531604b4b3b9fbc36437182781c3655c8ae/10/stretch-slim/Dockerfile - based on Debian Stretch, there is no `ps` in this image, just checked),
* loicsharma/baget (https://github.com/loic-sharma/BaGet/blob/master/Dockerfile, based on microsoft/dotnet:2.2-aspnetcore-runtime),
* my own based on microsoft/aspnetcore:2.0,
* my own based on mcr.microsoft.com/dotnet/core/aspnet:3.0

_Copied from https://github.com/dotnet/dotnet-docker/issues/1530#issuecomment-566775007 by @ktos_ 

And I just checked - `couchdb:latest` is Debian Stretch based, however it installs `procps` because couchdb requires it: https://github.com/apache/couchdb-pkg/blob/master/debian/control#L38

_Copied from https://github.com/dotnet/dotnet-docker/issues/1530#issuecomment-567219203 by MichaelSimons_

@dbreshears - Is this something that falls under your area of ownership?  If not do you know who does?

The UX doesn't seem ideal here.

1. I would expect a better error message indicating `ps` is required when it is not found.  
2. Given `ps` is not included in the Debian base OS image, what is your recommendation here?  Is it possible for the tooling to dynamically install any dependencies it requires?

_Copied from https://github.com/dotnet/dotnet-docker/issues/1530#issuecomment-567226668 by @dbreshears_

@gregg-miskelly, is this something you can help with?

_Copied from https://github.com/dotnet/dotnet-docker/issues/1530#issuecomment-567249893 by @gregg-miskelly_

@dbreshears can you transfer this issue to Microsoft/MIEngine? CC @pieandcakes

**Comment by pieandcakes** [comment]
This will be fixed in the next Preview release of Visual Studio 2019 version 16.5

**Comment by eitanhs** [comment]
@pieandcakes - 
Hi, after installing the said VS Preview version,
The specific error mentioned above is gone, but another one comes instead:
![image](https://user-images.githubusercontent.com/52374897/75236578-a6b14d00-57c6-11ea-92dd-e86192ff66fa.png)

I tried to execute the command manually in my docker host to see why it fails (`docker exec -it my_container /bin/sh "/root/.vs-debugger/Get                                                                                                                                                             VsDbg.sh" -v vs2019 -l "/root/.vs-debugger/vs2019" -a "/remote_debugger"
`):
```
Info: Previous installation at '/root/.vs-debugger/vs2019' not found
Info: Using vsdbg version '16.3.10904.1'
Using arguments
    Version                    : 'vs2019'
    Location                   : '/root/.vs-debugger/vs2019'
    SkipDownloads              : 'false'
    LaunchVsDbgAfter           : 'false'
    RemoveExistingOnUpgrade    : 'false'
Info: Using Runtime ID 'linux-x64'
Downloading https://vsdebugger.azureedge.net/vsdbg-16-3-10904-1/vsdbg-linux-x64.                                                                                                                                                             zip

 

ERROR: Command 'unzip' not found. Install 'unzip' for this script to work.
```

I thought it have something to do with the base image I was using -`mcr.microsoft.com/dotnet/core/aspnet:3.1`m so I changed my container base image to `mcr.microsoft.com/dotnet/core/sdk:3.1` but the same issue (unzip not found) still exist.

**Comment by pieandcakes** [comment]
@eitanhs the dotnet core debugger (`vsdbg`) requires `unzip` to be installed in the container. You can either add a line in the `dockerfile` to install `unzip` or install it manually from the command line. Once its installed, it will work.

**Comment by eitanhs** [comment]
@pieandcakes Thanks, that's what I eventually ended up doing...
I just want to point out that IMHO it is a weird design decision not to include the tools required to enable remote debugging even in SDK image...

If you agree with me and can point me to the relevant issue tracker, I will be glad to open an issue on the regard.
Thanks!

**Comment by pieandcakes** [comment]
@eitanhs I've tried to get the owners of the dotnet containers to add unzip but they seem to not want to do it. unfortunately i don't know if they have a public facing way to suggest a change.

**Comment by MichaelSimons** [comment]
.NET Core Docker issues can be logged at https://github.com/dotnet/dotnet-docker/issues.

@pieandcakes - Why isn't a tarball being used for this Linux scenario versus a zip?  Tar is included in the Linux images.  Adding additional packages such as unzip to the .NET Core runtime images is going to be met with resistance from the large number of customers who want slim images.

**Comment by pieandcakes** [comment]
@gregg-miskelly Can probably clarify better but if I remember the reason why its because we create the zip files on Windows and theres no good way to create a tarball in our build machines on Windows.

**Comment by gregg-miskelly** [comment]
@MichaelSimons @pieandcakes That is what I recall also. Though maybe there are better options for creating tarballs that we just failed to find.

**Comment by MichaelSimons** [comment]
From a Linux container perspective I think the usability of zips and requiring `unzip` to be installed within the container is a limiting factor.  [`tar` has been supported in Windows for sometime now](https://techcommunity.microsoft.com/t5/containers/tar-and-curl-come-to-windows/ba-p/382409).  Can you make use of it within your builds to produce tarballs?

**Comment by pieandcakes** [comment]
We can take another look and see if we can switch what is being generated.
