### ISSUE TITLE
Project doesn't build in 2020

### ISSUE THREAD

**Issue by puremourning** [microsoft/MIEngine#949]
Apologies if i'm missing something obvious, but I current can't build the MIEngine project.

I'm getting obscure errors "The specified version string does not conform to the required format - major.minor.build.revision". 

This seems be because the build number is guessed based on the year the project was created (2013) and the date (4th Jan). The current year delta from 2013 is used as the first part of the `build` version (it's currently 7). This leads to a `build` version > `65536` (`70104`) which fails the build. I guess I could work around this, but am I the only one experiencing this ? 

```
[assembly: System.Reflection.AssemblyFileVersionAttribute("14.0.70104.0")]
```

![image](https://user-images.githubusercontent.com/10584846/71766250-ced2ad00-2ef5-11ea-9bff-ac3b7c62670c.png)

I worked around it by changing `build\version.settings.targets` to set the `VersionZeroYear` to `2019` but clearly that's not the solution:

```diff
C:\Users\ben\source\repos\microsoft\MIEngine>git diff
diff --git a/build/version.settings.targets b/build/version.settings.targets
index ee094ea..3e77b94 100644
--- a/build/version.settings.targets
+++ b/build/version.settings.targets
@@ -5,7 +5,7 @@
     <!-- Note: If you change the version number, make sure that you notify partner teams such as C++ IOT -->
     <MajorVersion>14</MajorVersion>
     <MinorVersion>0</MinorVersion>
-    <VersionZeroYear>2013</VersionZeroYear>
+    <VersionZeroYear>2019</VersionZeroYear>

     <!--Compute the major and minor build number-->
     <!--Team build passes the build number in the BUILD_BUILDNUMBER variable. It has the format 'Master_20140922.4' where

C:\Users\ben\source\repos\microsoft\MIEngine>                    
```

**Comment by puremourning** [comment]
Maybe the year should go in `BuildNumberMajor` and the month/day in `BuildNumberMinor` ?

**Comment by gregg-miskelly** [comment]
Thanks! Oops. Should have dealt with this a long time ago.
