### ISSUE TITLE
Environment variables are not additive

### ISSUE THREAD

**Issue by Smit-tay** [microsoft/MIEngine#990]
If I set an environment variable that depends upon another variable, it is not dereferenced correctly

Example:

"environment": [
                    {"name":"VAR1",
                        "value": "${workspaceFolder}"},
                    {"name":"VAR2",
                         "value": "${VAR1}"},                                            

The result is:                ],
VAR1=/home/jack/dev/
VAR2=${VAR1}

Expected result is:
VAR1=/home/jack/dev/
VAR2=/home/jack/dev/

Since the built-in variable ${workspaceFolder} is being dereferenced (and any other number of built-ins too) there's no reason the same parser can't look for all other extant environment variables too.

You may run into an infinite loop, so it's important that a single pass is performed new variable being set, scanning for existing known variables only once.  Siince the syntax is already defined as  "${VARIABLE}" this should be trivial.

**Comment by pieandcakes** [comment]
@Smit-tay The parsing needs to be done in VS Code. This parsing isn't done in MIEngine. Please file this issue on the VS Code C++ Extension github page.
