### ISSUE TITLE
MIEngine not using envFile properly

### ISSUE THREAD

**Issue by Smit-tay** [microsoft/MIEngine#991]
See:  [MIEngine can't start after setting PATH #979](https://github.com/microsoft/MIEngine/issues/979)

**Comment by pieandcakes** [comment]
MIEngine doesn't handle `envFile`. This is a VS Code C++ extension concept. Please file the issue there.

**Comment by Smit-tay** [comment]
I'm not sure I understand your statement.

MIEngine uses the environment, or at least passes it to the debugger
Is the environment being passed to MIEngine ?

**Comment by pieandcakes** [comment]
>MIEngine uses the environment, or at least passes it to the debugger
Is the environment being passed to MIEngine ?

Correct. `environment` is handled by MIEngine. `envFile` which you are referencing is a VS Code C++ extension concept that the extension expands into added properties within the `environment` block.

**Comment by Smit-tay** [comment]
Sorry, I don't use Windows, or develop C# (which seems to be the language used), so it's not 100% clear reading the source.

I can see that environment is now being passed correctly to the debugee.  I am able to correctly set LD_LIBRARY_PATH via "environment" and exclude system libraries of the same name from my debug environment. 
 
But the original problem exists when using "envFile" instead of "environment".  In that case the environment variables declared in the file are not passed to the debugee.  

What you seem to be saying is that envFile is not passing it's variables on to to MIEngine.  

That's strange, because I had the same behavior if I modified PATH via "environment" or "envFile" - i.e. I could remove the path to "sh" and then the generated script couldn't be run since "sh" wasn't found.

**Comment by pieandcakes** [comment]
> What you seem to be saying is that envFile is not passing it's variables on to to MIEngine.

What I'm saying is that `envFile` is not a property that MIEngine (this repo) understands. It is only used by the VSCode C++ extension and the bug needs to be filed there. Their issue page is at https://github.com/microsoft/vscode-cpptools/issues. 

The extension code takes the `envFile` you give it and then adds it to the `environment` block that is passed to MIEngine. Therefore this is not a bug in MIEngine.
