### ISSUE TITLE
Implement Function Breakpoints for C#

### ISSUE THREAD

**Issue by loligans** [microsoft/MIEngine#997]
The C# debugger seems to be very good. One pain point I have is that I am unable to set breakpoints on chained functions.

As a user I would like to be able to set breakpoints in between chained function calls.

The functionality would be tremendously helpful when debugging startup or initialization code. Really anywhere you may encounter chained function calls.

**Comment by gregg-miskelly** [comment]
This is tracked with https://github.com/OmniSharp/omnisharp-vscode/issues/295
